---
- hosts: all
  connection: local
  become: true
  roles:
    - base

- hosts: all
  connection: local
  become: true
  pre_tasks:
    - name: pre-run | [Arch] update package cache
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

- hosts: workstation:laptop
  connection: local
  become: true
  roles:
    - role: workstation
      when: ansible_hostname in groups["workstation"] or ansible_hostname in groups["laptop"]

- hosts: server
  connection: local
  become: true
  roles:
    - role: server
      when: ansible_hostname in groups["server"]
...
