---
- hosts: "all:!lab"
  connection: local
  become: true
  roles:
    - base

- hosts: "all:!lab"
  connection: local
  become: true
  pre_tasks:
    - name: pre-run | [Arch] update package cache
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_facts['distribution'] == "Archlinux"

- hosts: workstation:laptop
  connection: local
  become: true
  roles:
    - role: workstation

- hosts: server
  connection: local
  become: true
  roles:
    - role: server

- hosts: lab
  connection: ssh
  become: true
  roles:
    - role: lab
...
