#+TITLE: ansible-provision
#+AUTHOR: Rafael Ito
#+DESCRIPTION: Ansible-pull automation to provision desktop/laptop/server config and dotfiles consistently.
#+STARTUP: showeverything
#+auto_tangle: t

* Table of Contents :toc_3:
- [[#tldr][TL;DR]]
- [[#description][Description]]
- [[#inventory][Inventory]]

* TL;DR :noexport_1:
* Description
Automagically configure your workstations, laptops, and servers from the ground up with a single command.
* Inventory
:PROPERTIES:
:header-args: :tangle inventory/hosts.yml
:END:
** Server
Meant to be used for servers. Currently, I'm using to host all my =homelab= self-hosted applications. Please check my other [[https://github.com/ito-rafael/lacasanostra][git repo]] for more information.
#+begin_src yml
server:
  hosts:
    srv1:
    srv2:
#+end_src
** Laptop
Meant to be used for laptops. It includes all my [[https://github.com/ito-rafael/keebab?tab=readme-ov-file#built-in-laptop][keyboard customization]] stuff.
#+begin_src yml
laptop:
  hosts:
    y2p-archlinux:
    vb-archlinux:
    ipf-archlinux:
#+end_src
** Workstation
Meant to be used for workstations. It includes the majority of tasks in this git repo (with exception of the keyboard customization, lab-specific tasks, and a few others).
#+begin_src yml
workstation:
  hosts:
    dxt-archlinux:
    catuaba.lbic.fee.unicamp.br:
#+end_src
** Lab
Meant to be used with standard =ansible= instead of =ansible-pull=. Configures the servers and workstations for the LBiC laboratory at University of Campinas.
#+begin_src yml
lab:
  children:
#+end_src
*** Server
#+begin_src yml :padline no
    lab_server:
      hosts:
        paubrasil.lbic.fee.unicamp.br:    # xxx.xx.xx.179
#+end_src
*** Workstation
#+begin_src yml :padline no
    lab_workstation:
      hosts:
        andira.lbic.fee.unicamp.br:        # xxx.xx.xx.162
        aroeira.lbic.fee.unicamp.br:       # xxx.xx.xx.163
        baoba.lbic.fee.unicamp.br:         # xxx.xx.xx.164
        barauna.lbic.fee.unicamp.br:       # xxx.xx.xx.165
        cajazeira.lbic.fee.unicamp.br:     # xxx.xx.xx.166
        cambuci.lbic.fee.unicamp.br:       # xxx.xx.xx.167
        castanheiro.lbic.fee.unicamp.br:   # xxx.xx.xx.168
        #catuaba.lbic.fee.unicamp.br:       # xxx.xx.xx.169
        cedro.lbic.fee.unicamp.br:         # xxx.xx.xx.170
        embira.lbic.fee.unicamp.br:        # xxx.xx.xx.171
        gameleira.lbic.fee.unicamp.br:     # xxx.xx.xx.172
        imburana.lbic.fee.unicamp.br:      # xxx.xx.xx.173
        ipe.lbic.fee.unicamp.br:           # xxx.xx.xx.174
        jacarada.lbic.fee.unicamp.br:      # xxx.xx.xx.175
        jatoba.lbic.fee.unicamp.br:        # xxx.xx.xx.176
        jequitiba.lbic.fee.unicamp.br:     # xxx.xx.xx.177
        mogno.lbic.fee.unicamp.br:         # xxx.xx.xx.178
        #paubrasil.lbic.fee.unicamp.br:     # xxx.xx.xx.179
        peroba.lbic.fee.unicamp.br:        # xxx.xx.xx.180
        seringueira.lbic.fee.unicamp.br:   # xxx.xx.xx.181
        umbu.lbic.fee.unicamp.br:          # xxx.xx.xx.182
        canabis.lbic.fee.unicamp.br:       # xxx.xx.xx.183
#+end_src
** Rootless
Meant to be used with standard =ansible= instead of =ansible-pull=. Configures tools in rootless environmets.
#+begin_src yml
rootless:
  hosts:
    ssh.recod.ic.unicamp.br:
#+end_src
