#+TITLE: ansible-provision
#+AUTHOR: Rafael Ito
#+DESCRIPTION: Ansible-pull automation to provision desktop/laptop/server config and dotfiles consistently.
#+STARTUP: showeverything
#+auto_tangle: t

* Table of Contents :toc_3:
- [[#tldr][TL;DR]]
- [[#description][Description]]
- [[#inventory][Inventory]]
  - [[#server-1][Server]]
  - [[#laptop-1][Laptop]]
  - [[#workstation-1][Workstation]]
  - [[#lab][Lab]]
    - [[#server-2][Server]]
    - [[#workstation-2][Workstation]]
  - [[#rootless][Rootless]]

* TL;DR :noexport_1:
* Description
Automagically configure your workstations, laptops, and servers from the ground up with a single command.
* Inventory
:PROPERTIES:
:header-args: :tangle inventory/hosts.yml
:END:
** Server
Meant to be used for servers. Currently, I'm using to host all my =homelab= self-hosted applications. Please check my other [[https://github.com/ito-rafael/lacasanostra][git repo]] for more information.
#+begin_src yaml
server:
  hosts:
    srv1:
    srv2:
#+end_src
** Laptop
Meant to be used for laptops. It includes all my [[https://github.com/ito-rafael/keebab?tab=readme-ov-file#built-in-laptop][keyboard customization]] stuff.
#+begin_src yaml
laptop:
  hosts:
    #y2p-archlinux:  # RIP: Yoga 2 Pro
    #vb-archlinux:   # RIP: Viva-Bem
    ipf-archlinux:   # IdeaPad Flex 5i
#+end_src
** Workstation
Meant to be used for workstations. It includes the majority of tasks in this git repo (with exception of the keyboard customization, lab-specific tasks, and a few others).
#+begin_src yaml
workstation:
  hosts:
    dxt-archlinux:  # used for tests
    catuaba:        # personal machine @ LBiC
#+end_src
** Lab
Meant to be used with standard =ansible= instead of =ansible-pull=. Configures the servers and workstations for the LBiC laboratory at University of Campinas.
#+begin_src yaml
lab:
  vars:
    ansible_user: ansible
  children:
#+end_src
*** Server
#+begin_src yaml :padline no
    lab_server:
      hosts:
        paubrasil:    # xxx.xxx.xx.179
#+end_src
*** Workstation
#+begin_src yaml :padline no
    lab_workstation:
      hosts:
        andira:       # xxx.xxx.xx.162
        aroeira:      # xxx.xxx.xx.163
        baoba:        # xxx.xxx.xx.164
        barauna:      # xxx.xxx.xx.165
        cajazeira:    # xxx.xxx.xx.166
        cambuci:      # xxx.xxx.xx.167
        castanheiro:  # xxx.xxx.xx.168
        #catuaba:     # xxx.xxx.xx.169
        cedro:        # xxx.xxx.xx.170
        embira:       # xxx.xxx.xx.171
        gameleira:    # xxx.xxx.xx.172
        imburana:     # xxx.xxx.xx.173
        ipe:          # xxx.xxx.xx.174
        jacaranda:    # xxx.xxx.xx.175
        jatoba:       # xxx.xxx.xx.176
        jequitiba:    # xxx.xxx.xx.177
        mogno:        # xxx.xxx.xx.178
        #paubrasil:   # xxx.xxx.xx.179
        peroba:       # xxx.xxx.xx.180
        seringueira:  # xxx.xxx.xx.181
        umbu:         # xxx.xxx.xx.182
        canabis:      # xxx.xxx.xx.183
#+end_src
** Rootless
Meant to be used with standard =ansible= instead of =ansible-pull=. Configures tools in rootless environmets.
#+begin_src yaml
rootless:
  hosts:
    ssh.recod.ic.unicamp.br:  # Recod.ai
      ansible_user: rafael.ito
#+end_src
** Domain
Groups created with the only purpose to share the FQDN.
*** localhost
#+begin_src yaml
local:
  children:
    laptop:
  hosts:
    dxt-archlinux:
  vars:
    ansible_host: "{{ inventory_hostname }}.internal"
#+end_src
*** LBiC
Group created with the only purpose to share the same "secret_domain" =vault.yml=.
#+begin_src yaml
lbic:
  children:
    lab:
  hosts:
    catuaba:
  vars:
    ansible_host: "{{ inventory_hostname }}.{{ secret_domain }}"
#+end_src
