server:
  hosts:
    srv1:
    srv2:

laptop:
  hosts:
    #y2p-archlinux:  # RIP: Yoga 2 Pro
    #vb-archlinux:   # RIP: Viva-Bem
    ipf-archlinux:   # IdeaPad Flex 5i

workstation:
  hosts:
    dxt-archlinux:  # used for tests
    catuaba:        # personal machine @ LBiC

rootless:
  hosts:
    ssh.recod.ic.unicamp.br:  # Recod.ai
      ansible_user: rafael.ito

local:
  children:
    laptop:
  hosts:
    dxt-archlinux:
  vars:
    ansible_host: "{{ inventory_hostname }}.internal"

lbic:
  children:
    lab:
  hosts:
    catuaba:
  vars:
    ansible_host: "{{ inventory_hostname }}.{{ secret_domain }}"
