server:
  hosts:
    srv1:
    srv2:

laptop:
  hosts:
    #y2p-archlinux.internal:               # RIP: Yoga 2 Pro
    #vb-archlinux.internal:                # RIP: Viva-Bem
    ipf-archlinux.internal:                # IdeaPad Flex 5i

workstation:
  hosts:
    dxt-archlinux.internal:                # used for tests
    catuaba.lbic.fee.unicamp.br:           # LBiC's PC

lab:
  vars:
    ansible_user: ansible
  children:
    lab_server:
      hosts:
        paubrasil.lbic.fee.unicamp.br:    # xxx.xx.xx.179
    lab_workstation:
      hosts:
        andira.lbic.fee.unicamp.br:        # xxx.xx.xx.162
        aroeira.lbic.fee.unicamp.br:       # xxx.xx.xx.163
        baoba.lbic.fee.unicamp.br:         # xxx.xx.xx.164
        barauna.lbic.fee.unicamp.br:       # xxx.xx.xx.165
        cajazeira.lbic.fee.unicamp.br:     # xxx.xx.xx.166
        cambuci.lbic.fee.unicamp.br:       # xxx.xx.xx.167
        castanheiro.lbic.fee.unicamp.br:   # xxx.xx.xx.168
        #catuaba.lbic.fee.unicamp.br:       # xxx.xx.xx.169
        cedro.lbic.fee.unicamp.br:         # xxx.xx.xx.170
        embira.lbic.fee.unicamp.br:        # xxx.xx.xx.171
        gameleira.lbic.fee.unicamp.br:     # xxx.xx.xx.172
        imburana.lbic.fee.unicamp.br:      # xxx.xx.xx.173
        ipe.lbic.fee.unicamp.br:           # xxx.xx.xx.174
        jacaranda.lbic.fee.unicamp.br:     # xxx.xx.xx.175
        jatoba.lbic.fee.unicamp.br:        # xxx.xx.xx.176
        jequitiba.lbic.fee.unicamp.br:     # xxx.xx.xx.177
        mogno.lbic.fee.unicamp.br:         # xxx.xx.xx.178
        #paubrasil.lbic.fee.unicamp.br:     # xxx.xx.xx.179
        peroba.lbic.fee.unicamp.br:        # xxx.xx.xx.180
        seringueira.lbic.fee.unicamp.br:   # xxx.xx.xx.181
        umbu.lbic.fee.unicamp.br:          # xxx.xx.xx.182
        canabis.lbic.fee.unicamp.br:       # xxx.xx.xx.183

rootless:
  hosts:
    ssh.recod.ic.unicamp.br:               # Recod.ai
      ansible_user: rafael.ito
