server:
  hosts:
    srv1:
    srv2:

laptop:
  hosts:
    #y2p-archlinux:  # RIP: Yoga 2 Pro
    #vb-archlinux:   # RIP: Viva-Bem
    ipf-archlinux:   # IdeaPad Flex 5i

workstation:
  hosts:
    dxt-archlinux:  # used for tests
    catuaba:        # personal machine @ LBiC

lab:
  vars:
    ansible_user: ansible
  children:
    lab_experiments:
      hosts:
        paubrasil:    # xxx.xxx.xx.179
    lab_server:
      hosts:
        andira:       # xxx.xxx.xx.162
    lab_workstation:
      hosts:
        #andira:      # xxx.xxx.xx.162
        aroeira:      # xxx.xxx.xx.163
        baoba:        # xxx.xxx.xx.164
        barauna:      # xxx.xxx.xx.165
        cajazeira:    # xxx.xxx.xx.166
        cambuci:      # xxx.xxx.xx.167
        castanheiro:  # xxx.xxx.xx.168
        #catuaba:     # xxx.xxx.xx.169
        cedro:        # xxx.xxx.xx.170
        embira:       # xxx.xxx.xx.171
        gameleira:    # xxx.xxx.xx.172
        imburana:     # xxx.xxx.xx.173
        ipe:          # xxx.xxx.xx.174
        jacaranda:    # xxx.xxx.xx.175
        jatoba:       # xxx.xxx.xx.176
        jequitiba:    # xxx.xxx.xx.177
        mogno:        # xxx.xxx.xx.178
        #paubrasil:   # xxx.xxx.xx.179
        peroba:       # xxx.xxx.xx.180
        seringueira:  # xxx.xxx.xx.181
        umbu:         # xxx.xxx.xx.182
        canabis:      # xxx.xxx.xx.183

rootless:
  hosts:
    ssh.recod.ic.unicamp.br:  # Recod.ai
      ansible_user: rafael.ito

local:
  children:
    laptop:
  hosts:
    dxt-archlinux:
  vars:
    ansible_host: "{{ inventory_hostname }}.internal"

lbic:
  children:
    lab:
  hosts:
    catuaba:
  vars:
    ansible_host: "{{ inventory_hostname }}.{{ secret_domain }}"
