- name: system | cron | restart cron systemd service
  tags: ansible,cron
  systemd:
    name: "{{ cron_pkg }}"
    state: restarted

- name: system | ssh | restart ssh systemd service
  tags: ssh
  systemd:
    name: "{{ ssh_pkg }}"
    state: restarted
