- name: development | container | Podman install
  tags: dev,container,podman
  package:
    name:
      - podman          # tool and library to run OCI-based containers in pods
      - podman-compose  # script to run docker-compose.yml
