- name: development | container-podman | prevent packages conflict
  tags: system,podman
  package:
    name: docker
    state: absent

- name: development | container-podman | install Podman
  tags: dev,container,podman
  package:
    name:
      - podman          # tool and library to run OCI-based containers in pods
      - podman-compose  # script to run docker-compose.yml
      - podman-docker   # aliases to emulate Docker CLI

- name: development | container-podman | configure unqualified-search-registries
  tags: system,podman
  ansible.builtin.lineinfile:
    path: /etc/containers/registries.conf
    regexp: 'unqualified-search-registries ='
    line: 'unqualified-search-registries = ["docker.io", "quay.io"]'
    state: present

#- name: development | container-podman | configure short-name-mode
#  tags: system,podman
#  ansible.builtin.lineinfile:
#    path: /etc/containers/registries.conf
#    regexp: 'short-name-mode ='
#    line: 'short-name-mode = "disabled"'
#    state: present
