- name: development | container-podman | prevent packages conflict
  tags: dev,container,podman
  package:
    name: docker
    state: absent

- name: development | container-podman | install Podman
  tags: dev,container,podman
  package:
    name:
      - podman          # tool and library to run OCI-based containers in pods
      - podman-compose  # script to run docker-compose.yml
      - podman-docker   # aliases to emulate Docker CLI
  notify: development | container-podman | enable user-level socket via systemd service

- name: development | container-podman | configure unqualified-search-registries
  tags: dev,container,podman
  ansible.builtin.copy:
    dest: /etc/containers/registries.conf.d/00-unqualified-search.conf
    content: |
      unqualified-search-registries = ["docker.io", "quay.io"]
    owner: root
    group: root
    mode: '0644'

#- name: development | container-podman | configure short-name-mode
#  tags: dev,container,podman
#  ansible.builtin.copy:
#    dest: /etc/containers/registries.conf.d/01-short-name-mode.conf
#    content: |
#      short-name-mode = "disabled"
#    owner: root
#    group: root
#    mode: '0644'
