- name: include tasks for podman container
  tags: dev,container,podman
  import_tasks: container-podman.yml
  when: container == "podman"

- name: include tasks for docker container
  tags: dev,container,docker
  import_tasks: container-docker.yml
  when: container == "docker"
