- name: development | docker | install Docker Engine
  tags: dev,docker
  package:
    name: docker

- name: development | docker | start & enable Docker daemon
  tags: dev,docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: development | docker | install Docker Compose
  tags: dev,docker
  package:
    name: docker-compose
