- name: development | docker | install Docker Engine
  tags: dev,docker
  package:
    name: docker

- name: development | docker | start & enable Docker daemon
  tags: dev,docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: development | docker | install Docker Compose
  tags: dev,docker
  package:
    name: docker-compose

- name: development | docker | install Docker Buildx
  tags: dev,docker
  package:
    name: docker-buildx

- name: development | docker | add user to docker group
  tags: dev,docker,rafael,groups
  user:
    name: rafael
    append: yes
    groups: docker
