- name: users | ansible | create group
  tags: users,ansible
  group:
    name: ansible
    state: present

- name: users | ansible | create user
  tags: users,ansible
  user:
    name: ansible
    group: ansible
    groups: "{{ sudo_group }}"
    createhome: yes
    state: present
    system: yes
    shell: /bin/bash
