- name: users | ansible | create group
  tags: users,ansible
  group:
    name: ansible
    state: present

- name: users | ansible | create user
  tags: users,ansible
  user:
    name: ansible
    group: ansible
    groups: "{{ sudo_group }}"
    createhome: yes
    state: present
    system: yes
    shell: /bin/bash

- name: users | ansible | add sudoers file
  tags: users,ansible
  copy:
    src: files/users/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440
    validate: "/usr/bin/visudo -cf %s"
