- name: users | rafael | dotfiles | create dir
  tags: users,dotfiles,apply
  file:
    path: /home/rafael/.config
    state: directory
    owner: rafael
    group: rafael
    mode: 0700

- name: users | rafael | dotfiles | copy dotfiles
  tags: rafael,dotfiles
  copy:
    remote_src: yes
    src: /home/rafael/git/pc-general-config/{{ item.src }}
    dest: /home/rafael/{{ item.dest }}
    owner: rafael
    group: rafael
    mode: 0700
  with_items:
    - { src: 'zsh/.zshrc', dest: '.zshrc' }
    - { src: 'vim/vimrc', dest: '.vimrc' }