- name: users | rafael | create group
  tags: users,rafael
  group:
    name: rafael
    state: present

- name: users | rafael | create user
  tags: users,rafael
  user:
    name: rafael
    group: rafael
    groups: "{{ sudo_group }}"
    createhome: yes
    state: present
    system: yes
    shell: /usr/bin/zsh

- name: users | rafael | add sudoers file
  tags: users,rafael
  copy:
    src: files/users/sudoers_rafael
    dest: /etc/sudoers.d/rafael
    owner: root
    group: root
    mode: 0440
    validate: "/usr/bin/visudo -cf %s"
