- name: users | rafael | enable user lingering for systemd
  tags: users,rafael
  command:
    cmd: loginctl enable-linger rafael
    creates: /var/lib/systemd/linger/rafael

- name: users | rafael | add sudoers file
  tags: users,rafael,sudo
  copy:
    src: files/users/sudoers_rafael_workstation
    dest: /etc/sudoers.d/20_rafael_workstation
    owner: root
    group: root
    mode: 0440
    validate: "/usr/bin/visudo -cf %s"
