- name: software | packages | install general packages
  tags: software,packages
  package:
    name:
      - git            # version control
      - htop           # process viewer
      - lshw           # show hw info
      - man-db         # tools for reading manual pages
      - python3        # Python programming language
      - tmux           # terminal multiplexer
      - vim            # terminal text editor

- name: software | packages | install monitoring packages
  tags: software,packages
  package:
    name:
      - iputils-ping   # network ping
      - speedtest-cli  # Internet bandwidth test with speedtest.net
