# load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:

  # Initialization
  - import_tasks: software/ansible.yml                  # Ansible
  - import_tasks: users/rafael.yml                      # default user
  - import_tasks: users/ansible.yml                     # Ansible user
  - import_tasks: users/dotfiles-clone.yml              # dotfiles repo

  # Arch Linux exclusive
  - import_tasks: software/pacman.yml                   # pacman-contrib
  - import_tasks: users/aurman.yml                      # AUR user
  - import_tasks: software/paru.yml                     # paru (AUR helper)
  - import_tasks: software/ansible-aur.yml              # ansible-aur module
    when: ansible_distribution == "Archlinux"

  # System settings
  - import_tasks: system/audio.yml                      # PipeWire
  - import_tasks: system/bluetooth.yml                  # BlueZ
  - import_tasks: system/fonts.yml                      # fonts
  - import_tasks: system/gpu-nvidia.yml                 # GPU: NVIDIA
  - import_tasks: system/keeb-hwdb.yml                  # keyboard: hardware mod
  - import_tasks: system/keeb-kmonad.yml                # keyboard: QMK-like layers
  - import_tasks: system/keep-xremap.yml                # keyboard: software processing
  #- import_tasks: system/keeb-interception.yml         # keyboard: interception [deprecated]
  #- import_tasks: system/keeb-udevmon.yml              # keyboard: udevmon [deprecated]
  - import_tasks: system/networking.yml                 # NetworkManager

  # Applications
  - import_tasks: software/android.yml                  # Android
  - import_tasks: software/browser-brave.yml            # browser: Brave
  - import_tasks: software/browser-firefox.yml          # browser: Firefox
  - import_tasks: software/browser-chromium.yml         # browser: Chromium
  - import_tasks: software/display-manager-lightdm.yml  # LightDM + theme
  #- import_tasks: software/display-manager-sddm.yml     # SDDM [deprecated]
  - import_tasks: software/email-client.yml             # Thunderbird
  - import_tasks: software/media-spotify.yml            # Spotify
  - import_tasks: software/office-suite.yml             # LibreOffice
  - import_tasks: software/shell.yml                    # Zsh
  - import_tasks: software/ssh-agent.yml                # Keychain
  - import_tasks: software/statusline.yml               # Powerline
  - import_tasks: software/terminal.yml                 # kitty
  - import_tasks: software/utils.yml                    # general packages
  - import_tasks: software/window-manager.yml           # Sway

  # Development
  - import_tasks: dev/docker.yml                        # Docker
  - import_tasks: dev/emacs.yml                         # Doom Emacs
  - import_tasks: dev/jupyter.yml                       # Jupyter
  - import_tasks: dev/latex.yml                         # LaTeX
  - import_tasks: dev/python.yml                        # Python

  - import_tasks: users/rafael-groups.yml               # groups permissions
  - import_tasks: users/rafael-dotfiles.yml             # dotfiles
