# load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:

  # Arch Linux exclusive
  - include_tasks: software/pacman.yml            # pacman-contrib
  - include_tasks: users/aurman.yml               # AUR user
  - include_tasks: software/paru.yml              # paru (AUR helper)
  - include_tasks: software/ansible-aur.yml       # ansible-aur module
    when: ansible_distribution == "Archlinux"

  - import_tasks: system/networking.yml           # NetworkManager
  - import_tasks: software/shell.yml              # Zsh
  - import_tasks: software/terminal.yml           # kitty
  - import_tasks: software/window-manager.yml     # Sway
  - import_tasks: software/display-manager.yml    # LightDM + theme
  - import_tasks: software/statusline.yml         # Powerline

  - import_tasks: users/rafael-dotfiles.yml       # dotfiles
