# load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:

  # Arch Linux exclusive
  - include_tasks: software/pacman.yml            # pacman-contrib
  - include_tasks: users/aurman.yml               # AUR user
  - include_tasks: software/paru.yml              # paru (AUR helper)
  - include_tasks: software/ansible-aur.yml       # ansible-aur module
    when: ansible_distribution == "Archlinux"

  # System settings
  - import_tasks: system/networking.yml           # NetworkManager
  - import_tasks: system/audio.yml                # PipeWire
  - import_tasks: system/bluetooth.yml            # BlueZ
  - import_tasks: system/udevmon.yml              # keyboard remap
  - import_tasks: system/fonts.yml                # fonts

  # Applications
  - import_tasks: software/ssh-agent.yml          # Keychain
  - import_tasks: software/shell.yml              # Zsh
  - import_tasks: software/terminal.yml           # kitty
  - import_tasks: software/window-manager.yml     # Sway
  - import_tasks: software/display-manager.yml    # LightDM + theme
  - import_tasks: software/statusline.yml         # Powerline
  - import_tasks: software/utils.yml              # general packages
  - import_tasks: software/browser-brave.yml      # browser: Brave
  - import_tasks: software/browser-firefox.yml    # browser: Firefox
  - import_tasks: software/browser-chromium.yml   # browser: Chromium
  - import_tasks: software/media-spotify.yml      # Spotify
  - import_tasks: software/office-suite.yml       # LibreOffice

  - import_tasks: users/rafael-dotfiles.yml       # dotfiles
