# load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  - import_tasks: system/networking.yml           # NetworkManager
  - import_tasks: software/shell.yml              # Zsh
  - import_tasks: software/terminal.yml           # kitty

  # Arch Linux exclusive
  - include_tasks: software/pacman.yml            # pacman-contrib
  - include_tasks: software/paru.yml              # paru (AUR helper)
    when: ansible_distribution == "Archlinux"

  - import_tasks: software/window-manager.yml     # Sway
