- name: keyboard | cedilla | fix cedilla in en_US locale
  tags: keyboard,cedilla
  ansible.builtin.replace:
    path: /usr/share/X11/locale/en_US.UTF-8/Compose
    regexp: "{{ item.find }}"
    replace: "{{ item.replace }}"
  with_items:
    - { find: 'ć', replace: 'ç' }
    - { find: 'Ć', replace: 'Ç' }

#- name: keyboard | cedilla | export cedilla env vars
#  tags: keyboard,cedilla
#  lineinfile:
#    path: /etc/environment
#    line: "{{ item }}"
#    state: present
#  with_items:
#    - 'XMODIFIERS=@im=fcitx'
#    - 'GTK_IM_MODULE=fcitx'
#    - 'QT_IM_MODULE=fcitx'

- name: keyboard | cedilla | install fcitx5
  tags: keyboard,cedilla
  package:
    name:
      - fcitx5             # input method framework
      - fcitx5-configtool  # configuration tool for fcitx5
      - fcitx5-gtk         # fcitx5 GTK IM module and D-Bus client lib
      - fcitx5-qt          # fcitx5 Qt library (Qt5 & Qt6)

#- name: keyboard | cedilla | fix cedilla using input method (fcitx5)
#  tags: keyboard,cedilla
#  become_user: aurman
#  kewlfft.aur.aur:
#    name: wayland-cedilla-fix
#  when: ansible_facts['distribution'] == "Archlinux"
  tags: keyboard,cedilla
  with_items:
