- name: keyboard | kanata | install kanata
  tags: keyboard,kanata
  become_user: aurman
  kewlfft.aur.aur:
    name: kanata-bin
  when: ansible_facts['distribution'] == "Archlinux"

- name: keyboard | kanata | ensure kanata dirs exist
  tags: keyboard,kanata
  file:
    path: /home/rafael/.config/{{ item }}
    state: directory
    owner: rafael
    group: rafael
    mode: 0700
  with_items:
    - kanata
    - systemd/user

- name: keyboard | kanata | copy kanata dotfile
  tags: keyboard,kanata
  copy:
    src: /home/ansible/git/keebab/kanata/kanata.kbd
    dest: /home/rafael/.config/kanata/kanata.kbd
    remote_src: true
    owner: rafael
    group: rafael
    mode: 0600
  notify:
    - handler | get UID of the user
    - keyboard | kanata | try-restart systemd user service
    - keyboard | kanata | try-restart systemd global service

- name: keyboard | kanata | copy global systemd service
  tags: keyboard,kanata
  copy:
    src: /home/ansible/git/keebab/systemd/system/kanata.service
    dest: /etc/systemd/system/kanata.service
    remote_src: true
    owner: root
    group: root
    mode: 0600
  notify:
    - reload systemd services (system scope)
    - handler | get UID of the user
    - keyboard | kanata | try-restart systemd global service
    - keyboard | kanata | enable global systemd service

- name: keyboard | kanata | copy user systemd service
  tags: keyboard,kanata
  copy:
    src: /home/ansible/git/keebab/systemd/user/kanata.service
    dest: /home/rafael/.config/systemd/user/kanata.service
    remote_src: true
    owner: rafael
    group: rafael
    mode: 0600
  notify:
    - reload user systemd services (rafael)
    - handler | get UID of the user
    - keyboard | kanata | try-restart systemd user service
    - keyboard | kanata | disable user systemd service
