#- name: keyboard | virtual kbd | install wvkbd
#  tags: keyboard,wvkbd
#  become_user: aurman
#  kewlfft.aur.aur:
#    name: wvkbd
#  when: ansible_facts['distribution'] == "Archlinux"

- name: keyboard | virtual kbd | check if wvkbd-deskintl is installed
  tags: keyboard,wvkbd
  ansible.builtin.stat:
    path: /usr/bin/wvkbd-deskintl
  register: wvkbd_bin
  when: ansible_facts['distribution'] == "Archlinux"

- name: keyboard | virtual kbd | clone wvkbd to persistent Paru cache
  tags: keyboard,wvkbd
  become_user: aurman
  ansible.builtin.git:
    repo: 'https://aur.archlinux.org/wvkbd.git'
    dest: ~/.cache/paru/clone/wvkbd
    update: yes
  register: wvkbd_repo
  when: ansible_facts['distribution'] == "Archlinux"

- name: keyboard | virtual kbd | inject deskintl into wvkbd's PKGBUILD build()
  tags: keyboard,wvkbd
  become_user: aurman
  ansible.builtin.replace:
    path: ~/.cache/paru/clone/wvkbd/PKGBUILD
    regexp: '^(\s*)make (-C "\$pkgname-v\$pkgver")$'
    replace: '\1make LAYOUT=deskintl \2'
  when:
    - ansible_facts['distribution'] == "Archlinux"
    - (wvkbd_repo.changed) or (not wvkbd_bin.stat.exists)

- name: keyboard | virtual kbd | inject deskintl into wvkbd's PKGBUILD package()
  tags: keyboard,wvkbd
  become_user: aurman
  ansible.builtin.replace:
    path: ~/.cache/paru/clone/wvkbd/PKGBUILD
    regexp: '^(\s*)make (-C "\$pkgname-v\$pkgver" PREFIX=/usr DESTDIR="\$pkgdir" install)$'
    replace: '\1make LAYOUT=deskintl \2'
  when:
    - ansible_facts['distribution'] == "Archlinux"
    - (wvkbd_repo.changed) or (not wvkbd_bin.stat.exists)

- name: keyboard | virtual kbd | build and install wvkbd-deskintl
  tags: keyboard,wvkbd
  become_user: aurman
  ansible.builtin.command:
    cmd: makepkg -siCf --noconfirm
    chdir: ~/.cache/paru/clone/wvkbd
  when:
    - ansible_facts['distribution'] == "Archlinux"
    - (wvkbd_repo.changed) or (not wvkbd_bin.stat.exists)
