- name: software | keyboard | fix cedilla in en_US locale
  tags: system,keyboard,cedilla
  ansible.builtin.replace:
    path: /usr/share/X11/locale/en_US.UTF-8/Compose
    regexp: "{{ item.find }}"
    replace: "{{ item.replace }}"
  with_items:
    - { find: 'ć', replace: 'ç' }
    - { find: 'Ć', replace: 'Ç' }

- name: software | keyboard | export cedilla env vars
  tags: system,keyboard,cedilla
  lineinfile:
    path: /etc/environment
    line: "{{ item }}"
    state: present
  with_items:
    - 'GTK_IM_MODULE=cedilla'
    - 'QT_IM_MODULE=cedilla'
