- name: keyboard | KMonad | install KMonad
  tags: keyboard,kmonad
  package:
    name: kmonad

- name: system | keyboard | copy KMonad systemd service
  tags: keyboard,kmonad
  copy:
    src: /home/rafael/git/dotfiles/kmonad/kmonad.service
    dest: /etc/systemd/system/kmonad.service
    remote_src: true
    owner: root
    group: root
    mode: 0644

- name: keyboard | KMonad | ensure KMonad dirs exist
  tags: keyboard,kmonad
  file:
    path: /home/rafael/.config/kmonad
    state: directory
    owner: rafael
    group: rafael
    mode: 0700

- name: keyboard | KMonad | copy KMonad dotfile
  tags: keyboard,kmonad
  copy:
    src: /home/rafael/git/dotfiles/kmonad/inkl-1ru.kbd
    dest: /home/rafael/.config/kmonad/inkl-1ru.kbd
    remote_src: true
    owner: rafael
    group: rafael
    mode: 0600

- name: keyboard | KMonad | start KMonad global daemon
  tags: keyboard,kmonad
  systemd:
    name: kmonad
    enabled: true
    daemon_reload: true
    state: started
