- name: keyboard | XKB | ensure xkb dirs exist
  tags: keyboard,xkb
  file:
    path: /home/rafael/.config/{{ item }}
    state: directory
    owner: rafael
    group: rafael
    mode: 0700
  with_items:
    - xkb/compat
    - xkb/rules
    - xkb/symbols

- name: keyboard | XKB | copy xkb dotfiles
  tags: keyboard,xkb
  copy:
    remote_src: yes
    src: /home/ansible/git/keebab/xkb/{{ item.src }}
    dest: /home/rafael/.config/xkb/{{ item.dest }}
    owner: rafael
    group: rafael
    mode: 0600
  with_items:
    - { src: 'compat/capslock_led', dest: 'compat/capslock_led' }
    - { src: 'rules/evdev',         dest: 'rules/evdev' }
    - { src: 'symbols/fn_keys',     dest: 'symbols/fn_keys' }
    - { src: 'symbols/modifiers',   dest: 'symbols/modifiers' }
