- name: keyboard | cedilla | fix cedilla in en_US locale
  tags: keyboard,cedilla
  ansible.builtin.replace:
    path: /usr/share/X11/locale/en_US.UTF-8/Compose
    regexp: "{{ item.find }}"
    replace: "{{ item.replace }}"
  with_items:
    - { find: 'ć', replace: 'ç' }
    - { find: 'Ć', replace: 'Ç' }

#- name: keyboard | cedilla | export cedilla env vars
#  tags: keyboard,cedilla
#  lineinfile:
#    path: /etc/environment
#    line: "{{ item }}"
#    state: present
#  with_items:
#    - 'XMODIFIERS=@im=fcitx'
#    - 'GTK_IM_MODULE=fcitx'
#    - 'QT_IM_MODULE=fcitx'

- name: keyboard | cedilla | install fcitx5
  tags: keyboard,cedilla
  package:
    name:
      - fcitx5             # input method framework
      - fcitx5-configtool  # configuration tool for fcitx5
      - fcitx5-gtk         # fcitx5 GTK IM module and D-Bus client lib
      - fcitx5-qt          # fcitx5 Qt library (Qt5 & Qt6)

#- name: keyboard | cedilla | fix cedilla using input method (fcitx5)
#  tags: keyboard,cedilla
#  become_user: aurman
#  kewlfft.aur.aur:
#    name: wayland-cedilla-fix
#  when: ansible_facts['distribution'] == "Archlinux"

- name: keyboard | cedilla | ensure fcitx5 dirs exist
  tags: keyboard,cedilla
  file:
    path: /home/rafael/.config/{{ item }}
    state: directory
    owner: rafael
    group: rafael
    mode: 0700
  with_items:
    - fcitx5
    - environment.d

- name: keyboard | cedilla | copy fcitx5 dotfiles
  tags: keyboard,cedilla
  copy:
    src: /home/ansible/git/keebab/fcitx5/{{ item.src }}
    dest: /home/rafael/.config/{{ item.dest }}
    remote_src: true
    owner: rafael
    group: rafael
    mode: 0600
  with_items:
    - { src: fcitx5.conf, dest: fcitx5/fcitx5.conf }
    - { src: profile,     dest: environment.d/profile }
