- name: keyboard | udev/hwdb | copy udev/hwdb dotfile
  tags: keyboard,hwdb
  copy:
    src: /home/ansible/git/keebab/udev/hwdb.d/90-miryoku-colemak.hwdb
    dest: /etc/udev/hwdb.d/90-miryoku-colemak.hwdb
    remote_src: true
    owner: root
    group: root
    mode: 0644
  register: hwdb_config

- name: keyboard | udev/hwdb | rebuild the hardware database index (hwdb.bin)
  tags: keyboard,hwdb
  command: systemd-hwdb update
  when: hwdb_config.changed

- name: keyboard | udev/hwdb | copy systemd-hwdb-update service
  tags: keyboard,hwdb
  copy:
    src: /lib/systemd/system/systemd-hwdb-update.service
    dest: /etc/systemd/system/systemd-hwdb-update.service
    owner: root
    group: root
    mode: 0644

- name: keyboard | udev/hwdb | enable update on boot (comment line)
  tags: keyboard,hwdb
  lineinfile:
    path: /etc/systemd/system/systemd-hwdb-update.service
    line: '#ConditionNeedsUpdate=/etc'
    state: present
    regexp: '^.*(ConditionNeedsUpdate=)/.*$'
    insertafter: '^\[Unit\]$'

- name: keyboard | udev/hwdb | update udev rules on the fly
  tags: keyboard,hwdb
  command: udevadm trigger
