- name: keyboard | KMonad | install KMonad
  tags: keyboard,kmonad
  package:
    name: kmonad

- name: keyboard | KMonad | ensure KMonad dirs exist
  tags: keyboard,kmonad
  file:
    path: /home/rafael/.config/{{ item }}
    state: directory
    owner: rafael
    group: rafael
    mode: 0700
  with_items:
    - kmonad
    - systemd/user

- name: keyboard | KMonad | copy KMonad dotfile
  tags: keyboard,kmonad
  copy:
    src: /home/rafael/git/keebab/kmonad/inkl-1ru.kbd
    dest: /home/rafael/.config/kmonad/inkl-1ru.kbd
    remote_src: true
    owner: rafael
    group: rafael
    mode: 0600

- name: keyboard | KMonad | copy KMonad global systemd service
  tags: keyboard,kmonad
  copy:
    src: /home/rafael/git/keebab/systemd/system/kmonad.service
    dest: /etc/systemd/system/kmonad.service
    remote_src: true
    owner: root
    group: root
    mode: 0600

- name: keyboard | KMonad | copy KMonad user systemd service
  tags: keyboard,kmonad
  copy:
    src: /home/rafael/git/keebab/systemd/user/kmonad.service
    dest: /home/rafael/.config/systemd/user/kmonad.service
    remote_src: true
    owner: rafael
    group: rafael
    mode: 0600

- name: keyboard | KMonad | reload KMonad user service
  tags: keyboard,kmonad
  systemd:
    name: kmonad
    enabled: false
    daemon_reload: true
    state: stopped
    scope: user

- name: keyboard | KMonad | start KMonad global daemon
  tags: keyboard,kmonad
  systemd:
    name: kmonad
    enabled: true
    daemon_reload: true
    state: started
