- name: keyboard | ZSA | install Wally CLI
  tags: keyboard,zsa
  package:
    name: zsa-wally-cli

- name: keyboard | ZSA | install Keymapp & Kontroll
  tags: keyboard,zsa
  become_user: aurman
  kewlfft.aur.aur:
    name:
      - zsa-keymapp-bin
      - zsa-kontroll-bin

- name: keyboard | ZSA | copy udev rules for ZSA keyboards
  tags: keyboard,zsa
  become: yes
  copy:
    remote_src: yes
    src: /home/rafael/git/dotfiles/udev/rules.d/50-zsa.rules
    dest: /etc/udev/rules.d/50-zsa.rules
    owner: root
    group: root
    mode: 0600
