- name: keyboard | interception | install interception packages
  tags: keyboard,interception
  package:
    name:
      #- evtest                         # used to get scan codes of each key
      - interception-caps2esc
      - interception-dual-function-keys

- name: keyboard | interception | interception (space2meta)
  tags: keyboard,interception
  become_user: aurman
  aur:
    name:
      - interception-space2meta

- name: keyboard | interception | copy udevmon config file
  tags: keyboard,interception
  copy:
    src: files/udevmon/udevmon.yaml
    dest: /etc/interception/udevmon.yaml
    owner: root
    group: root
    mode: 0644
  register: udevmon_config

- name: keyboard | interception | restart udevmon daemon
  tags: keyboard,interception
  systemd:
    name: udevmon
    state: restarted
    enabled: yes
  when: udevmon_config.changed
