- name: keyboard | ydotool | install ydotool
  tags: keyboard,ydotool
  package:
    name: ydotool

- name: keyboard | ydotool | ensure systemd dir exist
  tags: keyboard,ydotool
  file:
    path: /home/rafael/.config/systemd/user
    state: directory
    owner: rafael
    group: rafael
    mode: 0700

- name: keyboard | ydotool | copy ydotool user systemd service
  tags: keyboard,ydotool
  copy:
    src: /home/rafael/git/keebab/systemd/user/ydotool.service
    dest: /home/rafael/.config/systemd/user/ydotool.service
    remote_src: true
    owner: rafael
    group: rafael
    mode: 0600

- name: keyboard | ydotool | start user ydotool daemon
  tags: keyboard,ydotool
  become_user: rafael
  systemd:
    name: ydotool
    enabled: true
    daemon_reload: true
    state: started
    scope: user
