- name: keyboard | ydotool | install ydotool
  tags: keyboard,ydotool
  package:
    name: ydotool

- name: keyboard | ydotool | ensure systemd dir exist
  tags: keyboard,ydotool
  file:
    path: /home/rafael/.config/systemd/user
    state: directory
    owner: rafael
    group: rafael
    mode: 0700

- name: keyboard | ydotool | copy ydotool user systemd service
  tags: keyboard,ydotool
  copy:
    src: /home/ansible/git/keebab/systemd/user/ydotool.service
    dest: /home/rafael/.config/systemd/user/ydotool.service
    remote_src: true
    owner: rafael
    group: rafael
    mode: 0600

- name: keyboard | ydotool | enable user lingering for systemd
  tags: keyboard,ydotool
  command:
    cmd: loginctl enable-linger rafael
    creates: /var/lib/systemd/linger/rafael

- name: keyboard | ydotool | enable user ydotool daemon
  tags: keyboard,ydotool
  become_user: rafael
  systemd:
    name: ydotool
    enabled: true
    daemon_reload: true
    state: stopped
    scope: user
