- name: keyboard | ydotool | install ydotool
  tags: keyboard,ydotool
  package:
    name: ydotool

- name: keyboard | ydotool | start user ydotool daemon
  tags: keyboard,ydotool
  become_user: rafael
  systemd:
    name: ydotool
    enabled: yes
    state: started
    scope: user
