- name: keyboard | xremap | install packages
  tags: keyboard,rust,xremap
  package:
    name:
      - rust  # Rust
      - dex   # DesktopEntry Execution (for XDG Autostart)

- name: keyboard | xremap | install xremap
  tags: keyboard,xremap
  community.general.cargo:
    name: xremap

#cargo install xremap --features sway

- name: keyboard | xremap | add user to input group
  tags: keyboard,xremap
  user:
    name: rafael
    append: yes
    groups: input

- name: keyboard | xremap | copy udev/rules.d file
  tags: keyboard,xremap
  copy:
    remote_src: true
    src: /home/rafael/git/dotfiles/udev/rules.d/input.rules
    dest: /etc/udev/rules.d/input.rules
    owner: root
    group: root
    mode: 0644

- name: keyboard | xremap | ensure xremap dir exists
  tags: keyboard,xremap
  file:
    path: /home/rafael/.config/xremap
    state: directory
    owner: rafael
    group: rafael
    mode: 0700

- name: keyboard | xremap | copy xremap dotfile
  tags: keyboard,xremap
  copy:
    remote_src: true
    src: /home/rafael/git/dotfiles/xremap/config.yml
    dest: /home/rafael/.config/xremap/config.yml
    owner: rafael
    group: rafael
    mode: 0600

- name: keyboard | xremap | copy xremap desktop entry (for XDG Autostart)
  tags: keyboard,xremap
  copy:
    remote_src: true
    src: /home/rafael/git/dotfiles/autostart/xremap.desktop
    dest: /home/rafael/.config/autostart/xremap.desktop
    owner: rafael
    group: rafael
    mode: 0600

- name: keyboard | xremap | ensure user systemd dir exists
  tags: keyboard,xremap
  file:
    path: /home/rafael/.config/systemd/user
    state: directory
    owner: rafael
    group: rafael
    mode: 0700
