- name: software | browser | install Brave
  tags: browser,brave
  become_user: aurman
  kewlfft.aur.aur:
    name:
      - brave-bin
      - brave-beta-bin

- name: software | browser | ensure Brave dir exist
  tags: browser,brave
  file:
    path: /etc/brave/policies/managed
    state: directory
    owner: root
    group: root
    mode: 0755

- name: software | browser | ensure Brave extensions dir exist
  tags: browser,brave
  #become: yes
  file:
    path: /etc/brave/policies/managed
    state: directory
    owner: root
    group: root
    mode: 0755

- name: software | browser | copy Brave extensions dotfile
  tags: browser,brave
  copy:
    src: /home/rafael/git/dotfiles/brave/extension_install_policy.json
    dest: /etc/brave/policies/managed/extension_install_policy.json
    remote_src: true
    owner: root
    group: root
    mode: 0644
