- name: software | browser Brave | set variables
  tags: browser,brave
  ansible.builtin.set_fact:
    brave_prefs_path: "/home/rafael/.config/BraveSoftware/Brave-Origin-Beta/Default/Preferences"
    brave_dotfiles_dir: "/home/ansible/git/dotfiles/brave"

- name: software | browser Brave | install Brave Origin
  tags: browser,brave
  become_user: aurman
  kewlfft.aur.aur:
    name:
      #- brave-bin
      #- brave-beta-bin
      - brave-origin-beta-bin
      - python-webdriver-manager  # used by Selenium for automated config
  when: ansible_facts['distribution'] == "Archlinux"

- name: software | browser Brave | install Xvfb for headless run
  tags: browser,brave
  ansible.builtin.package:
    name: xorg-server-xvfb

- name: software | browser Brave | ensure extensions dir exist
  tags: browser,brave
  file:
    path: /etc/brave/policies/managed
    state: directory
    owner: root
    group: root
    mode: 0755

- name: software | browser Brave | copy dotfiles
  tags: browser,brave
  copy:
    src: "{{ brave_dotfiles_dir }}/json/{{ item }}"
    dest: "/etc/brave/policies/managed/{{ item }}"
    remote_src: true
    owner: root
    group: root
    mode: 0644
  loop:
    - extension_install_policy.json  # install extensions
    - dev_mode.json                  # ensure developer mode is available
    - default_browser.json           # disable default browser check

- name: software | browser Brave | copy flags file
  tags: browser,brave
  copy:
    src: "{{ brave_dotfiles_dir }}/config/brave-flags.conf"
    dest: /home/rafael/.config/brave-origin-beta-flags.conf
    remote_src: true
    owner: rafael
    group: rafael
    mode: 0600

- name: software | browser Brave | disable hardware acceleration on ancient GPUs
  tags: browser,brave
  copy:
    src: "{{ brave_dotfiles_dir }}/json/hardware_acceleration.json"
    dest: /etc/brave/policies/managed/hardware_acceleration.json
    remote_src: true
    owner: root
    group: root
    mode: 0644
  when: nvidia_driver == "nouveau"

- name: software | browser Brave | copy initial_preferences file
  tags: browser,brave
  copy:
    src: "{{ brave_dotfiles_dir }}/config/initial_preferences"
    dest: /opt/brave.com/brave-origin-beta/initial_preferences
    remote_src: true
    owner: root
    group: root
    mode: 0644

- name: software | browser Brave | ensure .desktop files dir exists
  tags: browser,brave
  file:
    path: /home/rafael/.local/share/applications
    state: directory
    owner: rafael
    group: rafael
    mode: 0755

- name: software | browser Brave | copy brave-origin-beta desktop file
  tags: browser,brave
  copy:
    src: "{{ brave_dotfiles_dir }}/brave-origin-beta.desktop"
    dest: /home/rafael/.local/share/applications/brave-origin-beta.desktop
    remote_src: true
    owner: rafael
    group: rafael
    mode: 0600

#----------------------------------
# read-only block
#----------------------------------

- name: software | browser Brave | check if Preferences file exists
  tags: browser,brave
  become_user: rafael
  ansible.builtin.stat:
    path: "{{ brave_prefs_path }}"
  register: brave_prefs

- name: software | browser Brave | get current theme
  tags: browser,brave
  become_user: rafael
  ansible.builtin.command: "jq -r '.browser.theme.color_scheme2 // empty' {{ brave_prefs_path }}"
  changed_when: false
  register: brave_theme
  when: brave_prefs.stat.exists

- name: software | browser Brave | check if Brave is running
  tags: browser,brave
  ansible.builtin.command: set -o pipefail && pgrep -a -f "[o]pt/brave.com/brave-origin-beta/brave" | grep -v " --type=" | grep -v " --app="
  failed_when: false
  changed_when: false
  register: brave_running

#----------------------------------
# gatekeeper: abort if needed
#----------------------------------

- name: software | browser Brave | abort if Brave is currently open
  tags: browser,brave
  ansible.builtin.fail:
    msg: >
      [ABORTED] Brave is currently running and configuration updates are pending!
      Please close the browser manually (Web Apps are fine) and re-run the playbook to apply the changes safely.
  when:
    - brave_running.rc == 0
    - (not brave_prefs.stat.exists) or (brave_theme.stdout | default('') != "2")

#----------------------------------
# write block
#----------------------------------

- name: software | browser Brave | initial profile generation and script execution
  tags: browser,brave
  block:
    - name: software | browser Brave | generate Brave Origin profile (via Xvfb)
      become_user: rafael
      ansible.builtin.shell: |
        xvfb-run -a brave-origin-beta --skip-origin-startup-dialog --no-first-run --disable-gpu --disable-dev-shm-usage --ozone-platform=x11 --ansible-burn-in https://example.com > /dev/null 2>&1 &
        sleep 120
        pkill -15 -f "--ansible-burn-in" || true

    - name: software | browser Brave | wait for profile IO completion
      become_user: rafael
      ansible.builtin.pause:
        seconds: 3
  when:
    - not brave_prefs.stat.exists

- name: software | browser Brave | set dark theme
  tags: browser,brave
  become_user: rafael
  ansible.builtin.shell: >
    jq '.browser.theme.color_scheme2 = 2' "{{ brave_prefs_path }}" > "{{ brave_prefs_path }}.tmp" &&
    mv "{{ brave_prefs_path }}.tmp" "{{ brave_prefs_path }}"
  when: brave_theme.stdout | default('') != "2"

- name: software | browser Brave | run Python scripts to configure preferences & extensions
  tags: browser,brave
  become_user: rafael
  ansible.builtin.shell: "xvfb-run -a python3 {{ brave_dotfiles_dir }}/scripts/{{ item }}"
  loop:
    - content_font_and_zoom.py
    - preferences_developer_mode.py
    - preferences_block_translations.py
    - surfingkeys_allow_user_scripts.py
    - surfingkeys_advanced_mode.py
    - surfingkeys_load_settings.py
    - tab-session-manager_theme_dark.py
    - video-speed-controller_import_settings.py
  register: python_execution
  changed_when: "'Success' in python_execution.stdout"
