- name: software | browser | install Brave
  tags: browser,brave
  become_user: aurman
  kewlfft.aur.aur:
    name:
      - brave-bin
      - brave-beta-bin

- name: software | browser | copy Brave dotfiles
  tags: browser,brave
  copy:
    src: /home/rafael/git/dotfiles/brave/{{ item.src }}
    dest: /home/rafael/.config/{{ item.dest }}
    remote_src: true
    owner: rafael
    group: rafael
    mode: 0600
  with_items:
    - { src: 'brave-flags.conf', dest: 'brave-flags.conf' }

- name: software | browser | copy Brave Beta dotfiles
  tags: browser,brave
  copy:
    src: /home/rafael/git/dotfiles/brave-beta/{{ item.src }}
    dest: /home/rafael/.config/{{ item.dest }}
    remote_src: true
    owner: rafael
    group: rafael
    mode: 0600
  with_items:
    - { src: 'brave-beta-flags.conf', dest: 'brave-beta-flags.conf' }

- name: software | browser | ensure Brave dir exist
  tags: browser,brave
  file:
    path: /etc/brave/policies/managed
    state: directory
    owner: root
    group: root
    mode: 0755

- name: software | browser | ensure Brave extensions dir exist
  tags: browser,brave
  #become: yes
  file:
    path: /etc/brave/policies/managed
    state: directory
    owner: root
    group: root
    mode: 0755

- name: software | browser | copy Brave extensions dotfile
  tags: browser,brave
  copy:
    src: /home/rafael/git/dotfiles/brave/extension_install_policy.json
    dest: /etc/brave/policies/managed/extension_install_policy.json
    remote_src: true
    owner: root
    group: root
    mode: 0644
