- name: software | browser Zen | set variables
  tags: browser,zen
  ansible.builtin.set_fact:
    zen_distrib_path: "/opt/zen-browser-bin/distribution"
    zen_dotfiles_dir: "/home/ansible/git/dotfiles/zen"

- name: software | browser Zen | install Zen Browser
  tags: browser,zen
  become_user: aurman
  kewlfft.aur.aur:
    name: zen-browser-bin
  when: ansible_facts['distribution'] == "Archlinux"

- name: software | browser Zen | install extensions
  tags: browser,zen
  copy:
    src: "{{ zen_dotfiles_dir }}/policies.json"
    dest: "{{ zen_distrib_path }}/policies.json"
    remote_src: true
    owner: root
    group: root
    mode: 0644
