- name: software | browser Edge | install Microsoft Edge
  tags: browser,edge
  become_user: aurman
  kewlfft.aur.aur:
    name: microsoft-edge-stable-bin
  when: ansible_facts['distribution'] == "Archlinux"
