- name: software | display-manager | LightDM install
  tags: display-manager,lightdm
  package:
    name: lightdm

- name: software | display-manager | LightDM start daemon
  tags: display-manager,lightdm
  systemd:
    name: lightdm
    enabled: yes
    state: started
