- name: software | display-manager | LightDM install
  tags: display-manager,lightdm
  package:
    name:
      - lightdm                             # display manager
      - lightdm-webkit2-greeter             # greeter

- name: software | display-manager | LightDM install greeter
  tags: display-manager,lightdm
  become_user: aurman
  aur:
    name: lightdm-webkit-theme-aether-git   # greeter theme

- name: software | display-manager | LightDM setup "logind-check-graphical"
  tags: display-manager,lightdm
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    line: 'logind-check-graphical=true'
    state: present
    regexp: '^.*(logind-check-graphical=).*$'
    insertafter: '^\[LightDM\]$'

- name: software | display-manager | LightDM setup "sessions-directory"
  tags: display-manager,lightdm
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    line: 'sessions-directory=/usr/share/lightdm/sessions:/usr/share/xsessions:/usr/share/wayland-sessions'
    state: present
    regexp: '^.*(sessions-directory=.*/usr/share/wayland-sessions)$'
    insertafter: '^\[LightDM\]$'

- name: software | display-manager | LightDM setup "greeter-session"
  tags: display-manager,lightdm
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    line: 'greeter-session=lightdm-webkit2-greeter'
    state: present
    regexp: '.*(greeter-session=).*'
    insertafter: '^\[Seat:\*\]$'

- name: software | display-manager | LightDM setup "webkit_theme"
  tags: display-manager,lightdm
  lineinfile:
    path: /etc/lightdm/lightdm-webkit2-greeter.conf
    line: 'webkit_theme        = lightdm-webkit-theme-aether'
    state: present
    regexp: '(^webkit_theme.*= ).*$'
    insertafter: '^\[greeter\]$'

- name: software | display-manager | LightDM fix session launch script
  tags: display-manager,lightdm
  lineinfile:
    path: /etc/lightdm/Xsession
    line: 'sleep 1'
    state: present
    regexp: '^sleep 1'
    insertbefore: 'exec \$\@'

- name: software | display-manager | LightDM start daemon
  tags: display-manager,lightdm
  systemd:
    name: lightdm
    enabled: yes
    state: started
