- name: software | display-manager | LightDM install
  tags: display-manager,lightdm
  package:
    name:
      - lightdm                             # display manager
      - lightdm-webkit2-greeter             # greeter

- name: software | display-manager | LightDM install greeter
  tags: display-manager,lightdm
  become_user: aurman
  aur:
    name: lightdm-webkit-theme-aether-git   # greeter theme

- name: software | display-manager | LightDM setup "logind-check-graphical"
  tags: display-manager,lightdm
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    line: 'logind-check-graphical=true'
    state: present
    regexp: '^.*(logind-check-graphical=).*$'
    insertafter: '^\[LightDM\]$'

- name: software | display-manager | LightDM setup "sessions-directory"
  tags: display-manager,lightdm
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    line: 'sessions-directory=/usr/share/lightdm/sessions:/usr/share/xsessions:/usr/share/wayland-sessions'
    state: present
    regexp: '^.*(sessions-directory=.*/usr/share/wayland-sessions)$'
    insertafter: '^\[LightDM\]$'

- name: software | display-manager | LightDM setup "greeter-session"
  tags: display-manager,lightdm
  replace:
    path: /etc/lightdm/lightdm.conf
    after: '\[Seat:\*\]'
    before: '\[XDMCPServer\]'
    regexp: '.*(greeter-session=).*'
    replace: '\g<1>lightdm-webkit2-greeter'

- name: software | display-manager | LightDM setup "webkit_theme"
  tags: display-manager,lightdm
  replace:
    path: /etc/lightdm/lightdm-webkit2-greeter.conf
    after: '\[greeter\]'
    before: '\[branding\]'
    regexp: '(^webkit_theme.*= ).*$'
    replace: '\g<1>Aether'

- name: software | display-manager | LightDM start daemon
  tags: display-manager,lightdm
  systemd:
    name: lightdm
    enabled: yes
    state: started
