- name: software | distrobox | install Distrobox
  tags: scratchpad,distrobox
  package:
    name: distrobox

- name: software | distrobox | set variables for Brave Distrobox build
  tags: scratchpad,distrobox
  ansible.builtin.set_fact:
    container_name: "brave-origin-beta"
    dockerfile_path: "/home/ansible/git/dotfiles/distrobox/brave-origin-beta/Dockerfile"
    build_context_dir: "/home/ansible/git/dotfiles/brave"
    brave_host_dir: "/home/rafael/.config/BraveSoftware/Brave-Distrobox"

- name: software | distrobox | build Brave Origin image with podman
  tags: scratchpad,distrobox
  become_user: rafael
  containers.podman.podman_image:
    name: "{{ container_name }}"
    path: "{{ build_context_dir }}"
    build:
      file: "{{ dockerfile_path }}"
  register: image_build

- name: software | distrobox | check if Brave Origin container exists with podman
  tags: scratchpad,distrobox
  become_user: rafael
  ansible.builtin.command: "podman container exists {{ container_name }}"
  failed_when: container_check.rc not in [0, 1]
  changed_when: false
  register: container_check

# runs only if the image was updated, or the container is missing
- name: software | distrobox | setup and configure Distrobox
  tags: scratchpad,distrobox
  become_user: rafael
  when: image_build.changed or container_check.rc != 0
  block:
    - name: software | distrobox | delete Brave-Distrobox directory
      ansible.builtin.file:
        path: "{{ brave_host_dir }}"
        state: absent

    - name: software | distrobox | recreate fresh Brave-Distrobox directory
      ansible.builtin.file:
        path: "{{ brave_host_dir }}"
        state: directory
        mode: '0755'

    - name: software | distrobox | delete brave-origin-beta container
      ansible.builtin.command: "distrobox rm -f {{ container_name }}"
      # Only runs if container exists but needs recreation due to an image update
      when: container_check.rc == 0

    - name: software | distrobox | recreate brave-origin-beta container
      ansible.builtin.command: >
        distrobox create
        --name {{ container_name }}
        --image {{ container_name }}
        --volume {{ brave_host_dir }}:/home/rafael/.config/BraveSoftware

    - name: software | distrobox | pre-warm distrobox container
      ansible.builtin.command: "distrobox enter {{ container_name }} -- echo 'Container is ready!'"

    - name: software | distrobox | generate Brave Origin profile (via Xvfb)
      ansible.builtin.shell: |
        distrobox enter {{ container_name }} -- sh -c 'xvfb-run -a brave-origin-beta --skip-origin-startup-dialog --no-first-run --disable-gpu --disable-dev-shm-usage --ozone-platform=x11 https://example.com > /dev/null 2>&1 & sleep 15 && pkill -15 brave'

    - name: software | distrobox | wait for Brave Origin saving the profile
      ansible.builtin.pause:
        seconds: 3

    - name: software | distrobox | set Brave Origin dark theme
      ansible.builtin.shell: |
        distrobox enter {{ container_name }} -- sh -c 'jq ".browser.theme.color_scheme2 = 2" ~/.config/BraveSoftware/Brave-Origin-Beta/Default/Preferences > tmp.json && mv tmp.json ~/.config/BraveSoftware/Brave-Origin-Beta/Default/Preferences'

    - name: software | distrobox | run Python scripts to configure preferences & extensions
      #ansible.builtin.command: "distrobox enter {{ container_name }} -- python3 /usr/local/bin/{{ item }}"
      ansible.builtin.command: "distrobox enter {{ container_name }} -- xvfb-run -a python3 /usr/local/bin/{{ item }}"
      loop:
        - preferences_developer_mode.py
        - preferences_block_translations.py
        - surfingkeys_allow_user_scripts.py
        - surfingkeys_advanced_mode.py
        - surfingkeys_load_settings.py

    - name: software | distrobox | delete old Distrobox desktop entries
      ansible.builtin.shell: "rm -rf /home/rafael/.local/share/applications/{{ container_name }}*"

    - name: software | distrobox | generate Distrobox desktop file
      ansible.builtin.command: >
        distrobox enter {{ container_name }} -- 
        distrobox-export --app {{ container_name }} --extra-flags "--no-default-browser-check"
