- name: software | distrobox | install Distrobox
  tags: scratchpad,distrobox
  package:
    name: distrobox

- name: software | distrobox | set variables for Brave Distrobox build
  tags: scratchpad,distrobox
  ansible.builtin.set_fact:
    container_name: "brave-origin-beta"
    dockerfile_path: "/home/ansible/git/dotfiles/distrobox/brave-origin-beta/Dockerfile"
    build_context_dir: "/home/ansible/git/dotfiles/brave"
    brave_host_dir: "/home/rafael/.config/BraveSoftware/Brave-Distrobox"

- name: software | distrobox | build Brave Origin image with podman
  tags: scratchpad,distrobox
  become_user: rafael
  containers.podman.podman_image:
    name: "{{ container_name }}"
    path: "{{ build_context_dir }}"
    build:
      file: "{{ dockerfile_path }}"
  register: image_build

- name: software | distrobox | check if Brave Origin container exists with podman
  tags: scratchpad,distrobox
  become_user: rafael
  ansible.builtin.command: "podman container exists {{ container_name }}"
  failed_when: container_check.rc not in [0, 1]
  changed_when: false
  register: container_check

# runs only if the image was updated, or the container is missing
- name: software | distrobox | setup and configure Distrobox
  tags: scratchpad,distrobox
  become_user: rafael
  when: image_build.changed or container_check.rc != 0
  block:
    - name: software | distrobox | delete Brave-Distrobox directory
      ansible.builtin.file:
        path: "{{ brave_host_dir }}"
        state: absent

    - name: software | distrobox | recreate fresh Brave-Distrobox directory
      ansible.builtin.file:
        path: "{{ brave_host_dir }}"
        state: directory
        mode: '0755'

    - name: software | distrobox | delete brave-origin-beta container
      ansible.builtin.command: "distrobox rm -f {{ container_name }}"
      # Only runs if container exists but needs recreation due to an image update
      when: container_check.rc == 0

    - name: software | distrobox | recreate brave-origin-beta container
      ansible.builtin.command: >
        distrobox create
        --name {{ container_name }}
        --image {{ container_name }}
        --volume {{ brave_host_dir }}:/home/rafael/.config/BraveSoftware
