- name: software | display-manager | SDDM install
  tags: display-manager,sddm
  package:
    name: sddm

- name: software | display-manager | SDDM start daemon
  tags: display-manager,sddm
  systemd:
    name: sddm
    enabled: yes
    state: started

- name: software | display-manager | SDDM xrandr config
  tags: display-manager,sddm
  copy:
    src: /home/rafael/git/dotfiles/scripts/sddm-outputs.sh
    dest: /usr/share/sddm/scripts/Xsetup
    remote_src: true
    owner: root
    group: root
    mode: 0755
