- name: software | email | uninstall Thunderbird
  tags: email,betterbird
  package:
    state: absent
    name: thunderbird

- name: software | email | install Betterbird
  tags: email,betterbird
  ansible.builtin.package:
    name: betterbird-bin
  when: ansible_facts['distribution'] == "Archlinux"

- name: software | email | ensure Betterbird dir exists
  tags: email,betterbird
  file:
    path: /home/rafael/.thunderbird/default
    state: directory
    owner: rafael
    group: rafael
    mode: 0700

- name: software | email | ensure Betterbird policies dir exists
  tags: email,betterbird
  file:
    path: /etc/betterbird/policies
    state: directory
    owner: root
    group: root
    mode: 0755

- name: software | email | copy static Betterbird dotfiles
  tags: email,betterbird
  copy:
    remote_src: true
    src: /home/ansible/git/dotfiles/thunderbird/profiles_betterbird.ini
    dest: /home/rafael/.thunderbird/profiles.ini
    owner: rafael
    group: rafael
    mode: 0600

- name: software | email | set Betterbird policies
  tags: email,betterbird
  copy:
    remote_src: true
    src: /home/ansible/git/dotfiles/thunderbird/policies.json
    dest: /etc/betterbird/policies/policies.json
    owner: root
    group: root
    mode: 0600

- name: software | email | template Betterbird user.js
  tags: email,betterbird
  template:
    src: /home/ansible/git/dotfiles/thunderbird/user.js.j2
    dest: /home/rafael/.thunderbird/default/user.js
    owner: rafael
    group: rafael
    mode: 0600
  vars:
    email_personal_gmail:       "{{ lookup('pipe', 'sudo -u rafael pass show email/personal_gmail') | trim }}"
    email_academic_unicamp:     "{{ lookup('pipe', 'sudo -u rafael pass show email/academic_unicamp') | trim }}"
    email_personal_promotional: "{{ lookup('pipe', 'sudo -u rafael pass show email/personal_promotional') | trim }}"
    email_personal_outlook:     "{{ lookup('pipe', 'sudo -u rafael pass show email/personal_outlook') | trim }}"
  no_log: true

#- name: software | email | install External Editor Revived for Betterbird
#  tags: email,betterbird
#  ansible.builtin.package:
#    name: external-editor-revived
#  when: ansible_facts['distribution'] == "Archlinux"
