- name: software | media | install GStreamer codecs
  tags: media,audio
  package:
    name:
      - gst-plugins-good
      - gst-plugins-bad
      - gst-plugins-ugly
      - gst-libav
      - gst-plugin-pipewire

- name: software | media | install GStreamer codecs (hw video decoding)
  tags: media,audio
  package:
    name: gst-plugin-va
  when: nvidia_driver != "nouveau"

#- name: software | media | install music streaming applications
#  tags: media,spotify
#  become_user: aurman
#  kewlfft.aur.aur:
#    name:
#      - spotify
#      - youtube-music-bin
#      - spotube-bin
#  when: ansible_facts['distribution'] == "Archlinux"

- name: software | media | install tools
  tags: media,audio
  package:
    name:
      - fatsort         # sort media in disk by date
      - mediainfo       # bitrate and other info

- name: software | media | install puddletag
  tags: media,audio
  become_user: aurman
  kewlfft.aur.aur:
    name: puddletag
  when: ansible_facts['distribution'] == "Archlinux"

- name: software | media | install Picard
  tags: media,audio
  package:
    name: picard  # MusicBrainz tagger

- name: software | media | install MPD
  tags: media,audio
  package:
    name: mpd

- name: software | media | ensure MPD dirs exist
  tags: media,audio
  file:
    path: /home/rafael/{{ item }}
    state: directory
    owner: rafael
    group: rafael
    mode: 0700
  with_items:
    - .config/mpd
    - .local/share/mpd/playlists

- name: software | media | copy MPD dotfile
  tags: media,audio
  copy:
    src: /home/ansible/git/dotfiles/mpd/mpd.conf
    dest: /home/rafael/.config/mpd/mpd.conf
    remote_src: true
    owner: rafael
    group: rafael
    mode: 0600
  notify: software | media | restart MPD user systemd service

- name: software | media | install MPD clients
  tags: media,audio
  package:
    name:
      - mpc
      - ncmpcpp

- name: software | media | ensure ncmpcpp dir exists
  tags: media,audio
  file:
    path: /home/rafael/.config/ncmpcpp
    state: directory
    owner: rafael
    group: rafael
    mode: 0700

- name: software | media | copy ncmpcpp dotfile
  tags: media,audio
  copy:
    src: /home/ansible/git/dotfiles/ncmpcpp/config
    dest: /home/rafael/.config/ncmpcpp/config
    remote_src: true
    owner: rafael
    group: rafael
    mode: 0600
