- name: software | miscellaneous | IRPF Brazilian income tax program
  tags: misc,irpf
  become_user: aurman
  kewlfft.aur.aur:
    name: irpf
  when: ansible_facts['distribution'] == "Archlinux"

- name: software | miscellaneous | bank BB
  tags: misc,bank
  become_user: aurman
  kewlfft.aur.aur:
    name: warsaw-bin
  when: ansible_facts['distribution'] == "Archlinux"

- name: software | miscellaneous | install LocalSend
  tags: misc,tools
  become_user: aurman
  kewlfft.aur.aur:
    name:
      - localsend-bin  # share files/messages over LAN
  when: ansible_facts['distribution'] == "Archlinux"

- name: software | miscellaneous | copy LocalSend dotfile
  tags: misc,localsend,tools
  copy:
    remote_src: true
    src: /home/ansible/git/dotfiles/localsend/settings.json
    dest: /opt/localsend/settings.json
    owner: rafael
    group: rafael
    mode: 0600
  when: ansible_facts['distribution'] == "Archlinux"

- name: software | miscellaneous | install Mousam weather app
  tags: misc,weather
  become_user: aurman
  kewlfft.aur.aur:
    name:
      - mousam         # weather forecast
  when: ansible_facts['distribution'] == "Archlinux"

- name: software | miscellaneous | check if Mousam dconf settings differ
  tags: misc,weather
  become_user: rafael
  ansible.builtin.shell: |
    export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$(id -u)/bus"
    diff <(dconf dump /io/github/amit9838/mousam/) /home/ansible/git/dotfiles/mousam/dconf-settings.ini
  args:
    executable: /bin/bash
  register: mousam_dconf_diff
  changed_when: false
  # diff returns 0 if identical, 1 if different, >1 if there is an error (eg: file missing)
  failed_when: mousam_dconf_diff.rc not in [0, 1]

- name: software | miscellaneous | copy Mousam dconf settings
  tags: misc,weather
  become_user: rafael
  ansible.builtin.shell: |
    export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$(id -u)/bus"
    dconf load /io/github/amit9838/mousam/ < /home/ansible/git/dotfiles/mousam/dconf-settings.ini
  when: mousam_dconf_diff.rc == 1
