- name: software | notification | install dunst
  tags: notification,dunst
  package:
    name:
      - dunst      # customizable and lightweight notification-daemon
      - libnotify  # dunstify: notify-send replacement with extra features

- name: software | notification | ensure dunst dir exists
  tags: notification,dunst
  file:
    path: /home/rafael/.config/dunst
    state: directory
    owner: rafael
    group: rafael
    mode: 0700

- name: software | notification | copy dunst dotfiles
  tags: notification,dunst
  copy:
    remote_src: true
    src: /home/ansible/git/dotfiles/dunst/{{ item.name }}
    dest: /home/rafael/.config/dunst/{{ item.name }}
    owner: rafael
    group: rafael
    mode: "{{ item.mode }}"
  with_items:
    - { name: 'dunstrc',           mode: '0600' }
    - { name: 'sound-dispatch.sh', mode: '0700' }
    - { name: 'whatsapp.mp3',      mode: '0600' }

- name: software | notification | install fping
  tags: notification
  package:
    name: fping  # requerired by =wait_host_up.sh= script
