- name: software | output profile | install kanshi & nwg-displays
  tags: output,kanshi
  package:
    name:
      - nwg-displays  # GUI for output management in Sway/Hyprland
      - kanshi        # daemon for dynamic automatic output profile for Wayland
      - #wdisplays    # GUI for configuring Wayland outputs
      - #wlr-randr    # CLI for managing outputs in Wayland

- name: software | output profile | ensure kanshi dirs exist
  tags: output,kanshi
  file:
    path: /home/rafael/.config/{{ item }}
    state: directory
    owner: rafael
    group: rafael
    mode: 0700
  with_items:
    - kanshi
    - systemd/user

- name: software | output profile | copy kanshi dotfiles
  tags: output,kanshi
  copy:
    remote_src: true
    src: /home/ansible/git/dotfiles/kanshi/{{ item.src }}
    dest: /home/rafael/.config/{{ item.dest }}
    owner: rafael
    group: rafael
    mode: "{{ item.mode }}"
  loop:
    - { src: 'config',         dest: 'kanshi/config',               mode: "0700" }
    - { src: 'kanshi.service', dest: 'systemd/user/kanshi.service', mode: "0600" }
  notify:
    - handler | get UID of the user
    - reload user systemd services (rafael)
    - software | output profile | restart kanshi systemd user service
