- name: software | package-manager | pacman-contrib install
  package:
    name: pacman-contrib    # paccache, pactree, etc

- name: software | package-manager | paru prerequisites
  package:
    name:
      - base-devel
      - rust

- name: software | package-manager | paru repo git clone
  git:
    clone: yes
    repo: https://aur.archlinux.org/paru.git
    dest: /home/rafael/git/paru
