- name: software | package-manager | pacman-contrib install
  tags: pacman
  package:
    name: pacman-contrib

- name: software | package-manager | force pacman-key refresh keys
  tags: pacman,pacman-key
  pacman:
    name: archlinux-keyring
    state: latest
    force: yes

- name: software | package-manager | enable ParallelDownloads
  tags: pacman
  replace:
    path: /etc/pacman.conf
    regexp: '^.*(ParallelDownloads).*$'
    replace: '\g<1> = 5'
