- name: software | package-manager | pacman-contrib install
  tags: pacman
  package:
    name: pacman-contrib

- name: software | package-manager | force pacman-key refresh keys
  tags: pacman,pacman-key
  pacman:
    name: archlinux-keyring
    state: latest
    force: yes

- name: software | package-manager | enable parallel downloads
  tags: pacman
  replace:
    path: /etc/pacman.conf
    regexp: '^.*(ParallelDownloads).*$'
    replace: '\g<1> = 5'

- name: software | package-manager | enable multilib repository
  tags: pacman
  replace:
    path: /etc/pacman.conf
    regexp: '^#(\[multilib\]$\n)^#(Include.*)$'
    replace: '\g<1>\g<2>'

- name: software | package-manager | update cache after enabling multilib
  tags: pacman
  pacman:
    update_cache: true

- name: software | package-manager | install rebuild-detector
  tags: pacman,rebuild-detector
  package:
    name: rebuild-detector
    state: latest

- name: software | package-manager | install reflector
  tags: pacman,reflector
  package:
    name:
      - rsync       # prerequisite for reflector
      - reflector   # update /etc/pacman.d/mirrorlist sorting the mirrors by speed
    state: latest

- name: software | package-manager | install additional packages
  tags: pacman
  become_user: aurman
  kewlfft.aur.aur:
    name:
      - downgrade  # downgrade packages in Arch Linux
      - informant  # Arch Linux News reader and pacman hook
    state: latest
