- name: software | package-manager | paru prerequisites
  package:
    name:
      - base-devel
      - rust

- name: software | package-manager | paru repo git clone
  become_user: aurman
  git:
    clone: yes
    repo: https://aur.archlinux.org/paru.git
    dest: /home/aurman/git/paru

- name: software | package-manager | paru install
  become_user: aurman
  command: makepkg -si --noconfirm
  args:
    chdir: /home/aurman/git/paru
    creates: /usr/bin/paru
