- name: software | pdf viewer | install Evince
  tags: pdf,evince
  package:
    name: evince

- name: software | pdf viewer | install other packages
  tags: pdf,evince
  package:
    name: qpdf  # content-preserving PDF transformation system

- name: software | pdf viewer | install Zathura
  tags: pdf,zathura
  package:
    name:
      - zathura               # core package
      - tesseract-data-eng    # prerequisite for zathura-pdf-mupdf
      - zathura-pdf-mupdf     # support for EPUB, PDF and XPS via MuPDF
      - zathura-djvu          # support for DjVu
      #- zathura-ps           # support for PostScript

- name: software | pdf viewer | ensure zathura dir exist
  tags: pdf,zathura
  file:
    path: /home/rafael/.config/zathura
    state: directory
    owner: rafael
    group: rafael
    mode: 0700

- name: software | pdf viewer | copy zathura dotfile
  tags: pdf,zathura
  copy:
    src: /home/ansible/git/dotfiles/zathura/zathurarc
    dest: /home/rafael/.config/zathura/zathurarc
    remote_src: true
    owner: rafael
    group: rafael
    mode: 0600

- name: software | pdf viewer | install PDF.js
  tags: pdf,pdfjs
  ansible.builtin.package:
    name: pdfjs

- name: software | pdf viewer | ensure PDF.js dirs exist
  tags: pdf,pdfjs
  file:
    path: /home/rafael/.config/{{ item }}
    state: directory
    owner: rafael
    group: rafael
    mode: 0700
  loop:
    - scripts
    - systemd/user

- name: software | pdf viewer | copy script to start PDF.js server
  tags: pdf,pdfjs
  copy:
    remote_src: yes
    src: /home/ansible/git/dotfiles/scripts/pdfjs-server.py
    dest: /home/rafael/.config/scripts/pdfjs-server.py
    owner: rafael
    group: rafael
    mode: 0700
  notify:
    - handler | get UID of the user
    - reload user systemd services (rafael)
    - software | pdf viewer | restart user PDF.js systemd service

- name: software | pdf viewer | copy PDF.js user systemd service
  tags: pdf,pdfjs
  copy:
    src: /home/ansible/git/dotfiles/systemd/user/pdfjs.service
    dest: /home/rafael/.config/systemd/user/pdfjs.service
    remote_src: true
    owner: rafael
    group: rafael
    mode: 0600
  notify:
    - handler | get UID of the user
    - reload user systemd services (rafael)
    - software | pdf viewer | restart user PDF.js systemd service
