- name: software | pdf viewer | install Evince
  tags: pdf,evince
  package:
    name: evince

- name: software | pdf viewer | install Zathura
  tags: pdf,zathura
  package:
    name:
      - zathura
      - zathura-pdf-viewer

- name: software | pdf viewer | ensure zathura dir exist
  tags: pdf,zathura
  file:
    path: /home/rafael/.config/zathura
    state: directory
    owner: rafael
    group: rafael
    mode: 0700

- name: software | pdf viewer | copy zathura dotfile
  tags: pdf,zathura
  copy:
    src: /home/rafael/git/dotfiles/zathura/zathurarc
    dest: /home/rafael/.config/zathura/zathurarc
    remote_src: true
    owner: rafael
    group: rafael
    mode: 0600
