- name: software | pomodoro | install tomat
  tags: pomodoro
  kewlfft.aur.aur:
    name: tomat-bin
  when: ansible_facts['distribution'] == "Archlinux"

- name: software | pomodoro | ensure tomat dir exist
  tags: pomodoro
  file:
    path: /home/rafael/.config/tomat
    state: directory
    owner: rafael
    group: rafael
    mode: 0700

- name: software | pomodoro | copy tomat dotfile
  tags: pomodoro
  copy:
    remote_src: true
    src: /home/ansible/git/dotfiles/tomat/config.toml
    dest: /home/rafael/.config/tomat/config.toml
    owner: rafael
    group: rafael
    mode: 0600
  notify: software | pomodoro | restart tomat user systemd service

- name: software | pomodoro | copy tomat systemd service
  tags: pomodoro
  copy:
    src: /home/rafael/git/dotfiles/systemd/user/tomat.service
    dest: /home/rafael/.config/systemd/user/tomat.service
    remote_src: true
    owner: rafael
    group: rafael
    mode: 0600

- name: software | pomodoro | enable user tomat daemon
  tags: pomodoro
  become_user: rafael
  systemd:
    name: tomat
    enabled: true
    state: stopped
    daemon_reload: true
    scope: user
