- name: software | brightness | install DDC/CI tool & brightnessctl
  tags: software,brightness
  package:
    name:
      - brightnessctl  # screen brightness
      - ddcutil        # external monitor control
