- name: include tasks for hyprlock screen locker
  tags: screen-locker,hyprlock
  import_tasks: screenlocker-hyprlock.yml
  when: screen_locker == "hyprlock"

- name: include tasks for swaylock screen locker
  tags: screen-locker,swaylock
  import_tasks: screenlocker-swaylock.yml
  when: screen_locker == "swaylock"
