- name: software | brightness | install DDC/CI tool & brightnessctl
  tags: software,brightness
  package:
    name:
      - brightnessctl  # screen brightness
      - ddcutil        # external monitor control

- name: software | brightness | kernel driver for DDC/CI monitors
  tags: software,brightness
  become_user: aurman
  kewlfft.aur.aur:
    name:
      - ddcci-driver-linux-dkms-git
  when: ansible_facts['distribution'] == "Archlinux"

- name: software | brightness | copy the udev rules for external monitors
  tags: software,brightness
  copy:
    remote_src: true
    src: /home/ansible/git/dotfiles/udev/rules.d/99-ddcci.rules
    dest: /etc/udev/rules.d/99-ddcci.rules
    owner: root
    group: root
    mode: 0600
  notify: update udev rules on the fly
- name: software | brightness | set i2c-dev kernel module to load on boot
  tags: software,brightness
  copy:
    content: "i2c-dev\n"
    dest: /etc/modules-load.d/i2c-dev.conf
    owner: root
    group: root
    mode: 0644

- name: software | brightness | load i2c-dev kernel module immediately
  tags: software,brightness
  community.general.modprobe:
    name: i2c-dev
    state: present

- name: software | brightness | add user to i2c group
  tags: software,brightness,groups
  user:
    name: rafael
    append: yes
    groups: i2c
