- name: software | screen | install gammastep
  tags: gamma
  package:
    name: gammastep

- name: software | screen | ensure gammastep dir exists
  tags: gamma
  file:
    path: /home/rafael/.config/gammastep
    state: directory
    owner: rafael
    group: rafael
    mode: 0700

- name: software | screen | copy gammastep dotfile
  tags: gamma
  copy:
    remote_src: true
    src: /home/ansible/git/dotfiles/gammastep/config.ini
    dest: /home/rafael/.config/gammastep/config.ini
    owner: rafael
    group: rafael
    mode: 0600
