- name: software | brightness | install DDC/CI tool & brightnessctl
  tags: software,brightness
  package:
    name:
      - brightnessctl  # screen brightness
      - ddcutil        # external monitor control

- name: software | brightness | load i2c-dev kernel module immediately
  tags: software,brightness
  community.general.modprobe:
    name: i2c-dev
    state: present
