- name: software | semaphore | install Semaphore UI
  tags: semaphore
  become_user: aurman
  kewlfft.aur.aur:
    name: semaphore-bin
  when: ansible_facts['distribution'] == "Archlinux"

- name: software | semaphore | ensure semaphore dirs exist
  tags: semaphore
    file:
      path: /home/ansible/.config/{{ item }}
      state: directory
      owner: ansible
      group: ansible
      mode: 0700
  with_items:
    - semaphore
    - systemd/user

- name: software | semaphore | check if semaphore config already exists
  tags: semaphore
  ansible.builtin.stat:
    path: /home/ansible/.config/semaphore/config.json
  register: semaphore_config_file
