- name: software | statusline | Powerline install
  tags: statusline,powerline
  package:
    name:
      - powerline
      - powerline-fonts

- name: software | statusline | waybar install
  tags: statusline,waybar
  package:
    name: waybar

- name: software | statusline | ensure waybar dir exist
  tags: statusline,waybar
  file:
    path: /home/rafael/.config/waybar
    state: directory
    owner: rafael
    group: rafael
    mode: 0700
