- name: software | statusline | Powerline install
  tags: statusline,powerline
  package:
    name:
      - powerline
      - powerline-fonts

- name: software | statusline | waybar install
  tags: statusline,waybar
  package:
    name: waybar

- name: software | statusline | ensure waybar dir exist
  tags: statusline,waybar
  file:
    path: /home/rafael/.config/waybar
    state: directory
    owner: rafael
    group: rafael
    mode: 0700

- name: software | statusline | copy waybar dotfiles (launcher)
  tags: statusline,waybar
  copy:
    src: /home/rafael/git/dotfiles/waybar/waybar.sh
    dest: /home/rafael/.config/waybar/waybar.sh
    remote_src: true
    owner: rafael
    group: rafael
    mode: 0600
