- name: software | statusline | Powerline install
  tags: statusline,powerline
  package:
    name:
      - powerline
      - powerline-fonts

- name: software | statusline | waybar install
  tags: statusline,waybar
  package:
    name: waybar
