# IIO accelerometer sensor to input device proxy
- name: software | tablet | install iio-sensor-proxy acc sensor
  tags: tablet,2-in-1,autorotate
  package:
    name: iio-sensor-proxy
  when: inventory_hostname in groups['laptop']

# automatic screen rotation daemon
- name: software | tablet | check if rot8 is installed
  tags: tablet,2-in-1,autorotate
  ansible.builtin.stat:
    path: /usr/bin/rot8
  register: rot8_bin
  when:
    - ansible_facts['distribution'] == "Archlinux"
    - inventory_hostname in groups['laptop']

- name: software | tablet | clone rot8-git to persistent cache
  tags: tablet,2-in-1,autorotate
  become_user: aurman
  ansible.builtin.git:
    repo: 'https://aur.archlinux.org/rot8-git.git'
    dest: ~/.cache/paru/clone/rot8-git
    update: yes
  register: rot8_repo
  when:
    - ansible_facts['distribution'] == "Archlinux"
    - inventory_hostname in groups['laptop']

# custom build to bypass --locked flag error
- name: software | tablet | patch rot8-git PKGBUILD to remove --locked flag
  tags: tablet,2-in-1,autorotate
  become_user: aurman
  ansible.builtin.replace:
    path: ~/.cache/paru/clone/rot8-git/PKGBUILD
    regexp: '--locked\s*'
    replace: ''
  when:
    - ansible_facts['distribution'] == "Archlinux"
    - inventory_hostname in groups['laptop']
    - (rot8_repo.changed) or (not rot8_bin.stat.exists)

- name: software | tablet | build and install patched rot8-git
  tags: tablet,2-in-1,autorotate
  become_user: aurman
  ansible.builtin.command:
    cmd: makepkg -siCf --noconfirm
    chdir: ~/.cache/paru/clone/rot8-git
  when:
    - ansible_facts['distribution'] == "Archlinux"
    - inventory_hostname in groups['laptop']
    - (rot8_repo.changed) or (not rot8_bin.stat.exists)

- name: software | tablet | restore PKGBUILD to prevent dirty git tree
  tags: tablet,2-in-1,autorotate
  become_user: aurman
  ansible.builtin.command:
    cmd: git checkout PKGBUILD
    chdir: ~/.cache/paru/clone/rot8-git
  when:
    - ansible_facts['distribution'] == "Archlinux"
    - inventory_hostname in groups['laptop']
    - (rot8_repo.changed) or (not rot8_bin.stat.exists)
