- name: software | terminal | install kitty
  tags: terminal,kitty
  package:
    name: kitty

- name: software | terminal | ensure kitty dir exist
  tags: terminal,kitty
  file:
    path: /home/rafael/.config/kitty/themes
    state: directory
    owner: rafael
    group: rafael
    mode: 0700

- name: software | terminal | copy kitty dotfiles & themes
  tags: terminal,kitty
  copy:
    remote_src: true
    src: /home/ansible/git/dotfiles/kitty/{{ item }}
    dest: /home/rafael/.config/kitty/{{ item }}
    owner: rafael
    group: rafael
    mode: 0600
  with_items:
    - kitty.conf
    - themes/default.conf
    - themes/terminal.conf
    - themes/python.conf
    - themes/ssh.conf
    - themes/root.conf

- name: software | terminal | [root] ensure kitty dir exist
  tags: terminal,kitty
  file:
    path: /root/.config/kitty
    state: directory
    owner: root
    group: root
    mode: 0700

- name: software | terminal | [root] copy kitty dotfiles
  tags: terminal,kitty
  copy:
    remote_src: yes
    src: /home/ansible/git/dotfiles/kitty/themes/root.conf
    dest: /root/.config/kitty/root.conf
    owner: root
    group: root
    mode: 0600

- name: software | terminal | [root] change theme when root
  tags: terminal,kitty
  lineinfile:
    path: /root/.profile
    line: 'kitty @ set-colors /root/.config/kitty/root.conf'
    state: present
    create: true

- name: software | terminal | [root] change back theme when not root
  tags: terminal,kitty
  lineinfile:
    path: /root/.bash_logout
    line: 'kitty @ set-colors --reset'
    state: present
    create: true
