- name: software | terminal | kitty
  tags: terminal,kitty
  package:
    name: kitty

- name: software | terminal | copy dotfiles for kitty
  tags: terminal,kitty
  copy:
    src: /home/rafael/git/dotfiles/kitty/kitty.conf
    dest: /home/rafael/.config/kitty/kitty.conf
    remote_src: true
    owner: root
    group: root
    mode: 0600
