- name: software | terminal | install kitty
  tags: terminal,kitty
  package:
    name: kitty

- name: software | terminal | ensure kitty dir exist
  tags: terminal,kitty
  file:
    path: /home/rafael/.config/kitty/themes
    state: directory
    owner: rafael
    group: rafael
    mode: 0700

- name: software | terminal | copy kitty dotfiles & themes
  tags: terminal,kitty
  copy:
    remote_src: true
    src: /home/rafael/git/dotfiles/kitty/{{ item }}
    dest: /home/rafael/.config/kitty/{{ item }}
    owner: rafael
    group: rafael
    mode: 0600
  with_items:
    - kitty.conf
    - themes/default.conf
    - themes/terminal.conf
