- name: software | terminal | install kitty
  tags: terminal,kitty
  package:
    name: kitty

- name: software | terminal | ensure kitty dir exist
  tags: terminal,kitty
  file:
    path: /home/rafael/.config/kitty/themes
    state: directory
    owner: rafael
    group: rafael
    mode: 0700

- name: software | terminal | copy kitty dotfile
  tags: terminal,kitty
  copy:
    src: /home/rafael/git/dotfiles/kitty/kitty.conf
    dest: /home/rafael/.config/kitty/kitty.conf
    remote_src: true
    owner: rafael
    group: rafael
    mode: 0600
