- name: software | video | install OBS with Flatpak
  tags: video,obs
  community.general.flatpak:
    name: com.obsproject.Studio

- name: software | video | install mpv
  tags: video,mpv
  package:
    name: mpv

- name: software | video | install other applications
  tags: video
  package:
    name:
      - ffmpeg
