- name: software | video | install OBS with Flatpak
  tags: video,obs
  community.general.flatpak:
    name: com.obsproject.Studio

- name: software | video | install mpv
  tags: video,mpv
  package:
    name: mpv

- name: software | video | install MKVToolNix
  tags: video
  package:
    name:
      - mkvtoolnix-cli
      - mkvtoolnix-gui

#- name: software | video | install VLC (3.x)
#  tags: video,vlc
#  package:
#    state: absent
#    name:
#      - vlc
#      - vlc-plugins-base   # essential basic plugins
#      - vlc-plugins-extra  # FFmpeg, H.264/H.265, VA-API, MPEG
#      - zvbi               # for recording with VLC

#- name: software | video | install VLC (4.x) from AUR (Wayland support)
#  tags: video,vlc
#  ansible.builtin.package:
#    name: vlc-git
#  when: ansible_facts['distribution'] == "Archlinux"

- name: software | video | install other applications
  tags: video
  package:
    name:
      - ffmpeg                # FFmpeg: record, convert & stream video
      - v4l-utils             # Video4Linux tools
      - linux-headers         # prerequisite for V4L2 loopback
      - v4l2loopback-dkms     # V4L2 loopback devices
      - yt-dlp                # CLI video downloader
