- name: software | video | install OBS with Flatpak
  tags: video,obs
  community.general.flatpak:
    name: com.obsproject.Studio

- name: software | video | install mpv
  tags: video,mpv
  package:
    name: mpv

- name: software | video | install other applications
  tags: video
  package:
    name:
      - ffmpeg                # FFmpeg: record, convert & stream video
      - v4l-utils             # Video4Linux tools
      - linux-headers         # prerequisite for V4L2 loopback
      - v4l2loopback-dkms     # V4L2 loopback devices
