- name: software | wallpaper | ensure wallpaper dir exist
  tags: wallpaper
  file:
    path: /home/rafael/.config/wallpaper
    state: directory
    owner: rafael
    group: rafael
    mode: 0700

- name: software | wallpaper | copy images to wallpaper dir
  tags: wallpaper
  copy:
    src: /home/rafael/git/dotfiles/wallpaper/{{ item }}
    dest: /home/rafael/.config/wallpaper/{{ item }}
    remote_src: true
    owner: rafael
    group: rafael
    mode: 0600
  with_items:
    - 'croatia.jpg'
    - 'london.jpg'
    - 'piedras-rojas.jpg'
    - 'nasa.png'
