- name: software | widget | install eww
  tags: widget
  become_user: aurman
  kewlfft.aur.aur:
    name: eww
  when: ansible_facts['distribution'] == "Archlinux"

- name: software | widget | ensure eww dirs exists
  tags: widget
  file:
    path: /home/rafael/.config/{{ item }}
    state: directory
    owner: rafael
    group: rafael
    mode: 0700
  loop:
    - eww
    - icon

- name: software | widget | copy eww dotfiles
  tags: widget
  copy:
    remote_src: true
    src: /home/ansible/git/dotfiles/eww/{{ item }}
    dest: /home/rafael/.config/eww/{{ item }}
    owner: rafael
    group: rafael
    mode: 0600
  loop:
    - eww.yuck
    - eww.scss
    - volume.sh

- name: software | widget | copy eww icons
  tags: widget
  copy:
    remote_src: true
    src: /home/ansible/git/dotfiles/icon/{{ item }}
    dest: /home/rafael/.config/icon/{{ item }}
    owner: rafael
    group: rafael
    mode: 0600
  loop:
    - vol-mute.png
    - vol-low.png
    - vol-med.png
    - vol-high.png
