- name: software | window-manager | sway
  tags: wayland,sway
  package:
    name:
      - gnu-free-fonts      # prerequisite of sway
      - seatd               # prerequisite of sway
      - sway                # window manager / compositor
      - ruby                # prerequisite for i3bang (config preprocessor)

- name: software | window-manager | add user to seat group
  tags: wayland,sway,users,rafael
  user:
    name: rafael
    groups: seat
    append: yes

- name: software | window-manager | start seatd daemon
  tags: wayland,sway
  systemd:
    name: seatd
    enabled: yes
    state: started
