- name: software | window-manager | install i3wm
  tags: X11,i3
  package:
    name:
      - xorg-xserver        # XOrg
      - xorg-apps           # XOrg packages
      - ruby                # prerequisite for i3bang (config preprocessor)
      - perl-anyevent-i3    # layout saving
      - perl-json-xs        # layout saving
      - i3-wm               # i3 window manager

- name: software | window-manager | install i3wm locker
  tags: X11,i3
  become_user: aurman
  kewlfft.aur.aur:
    name: i3lock-color      # screen locker

- name: software | window-manager | general packages
  tags: X11,i3
  package:
    name:
      - xclip               # clipboard utils
      - imagemagick         # used by i3lock scripts

- name: software | window-manager | ensure i3wm dirs exist
  tags: X11,i3
  file:
    path: /home/rafael/.config/{{ item }}
    state: directory
    owner: rafael
    group: rafael
    mode: 0700
  with_items:
    - i3
    - i3lock

- name: software | window-manager | copy i3wm dotfiles
  tags: X11,i3
  copy:
    src: /home/rafael/git/dotfiles/i3-sway/_config_i3
    dest: /home/rafael/.config/i3/_config
    remote_src: true
    owner: rafael
    group: rafael
    mode: 0600
