- name: software | window-manager | install Sway
  tags: wayland,sway
  package:
    name:
      - seatd         # prerequisite of sway
      - sway          # window manager / compositor
      - ruby          # prerequisite for i3bang (config preprocessor)
      - sway-contrib  # community scripts for sway
      - swayidle      # idle manager
      - swaybg        # wallpaper tool

- name: software | window-manager | install portals
  tags: wayland,portals
  package:
    name:
      - xdg-desktop-portal      # XDG Desktop portal
      - xdg-desktop-portal-wlr  # xdg-desktop-portal backend for wlroots
      - xdg-desktop-portal-gtk  # xdg-desktop-portal backend using GTK

- name: software | window-manager | ensure xdg-desktop-portal dir exists
  tags: wayland,portals
  file:
    path: /home/rafael/.config/xdg-desktop-portal
    state: directory
    owner: rafael
    group: rafael
    mode: 0700

- name: software | window-manager | copy xdg-desktop-portal dotfile
  tags: wayland,portals
  copy:
    remote_src: true
    src: /home/rafael/git/dotfiles/xdg-desktop-portal/sway-portals.conf
    dest: /home/rafael/.config/xdg-desktop-portal/sway-portals.conf
    owner: rafael
    group: rafael
    mode: 0600

- name: software | window-manager | enable user lingering for systemd
  tags: wayland,portals
  command:
    cmd: loginctl enable-linger rafael
    creates: /var/lib/systemd/linger/rafael

- name: software | window-manager | enable xdg-desktop-portals user services
  tags: wayland,portals
  become_user: rafael
  systemd:
    name: "{{ item }}"
    enabled: true
    daemon_reload: false
    state: stopped
    scope: user
  loop:
    - "xdg-desktop-portal"
    - "xdg-desktop-portal-wlr"
    - "xdg-desktop-portal-gtk"

- name: software | window-manager | add user to seat group
  tags: wayland,sway,users,rafael
  user:
    name: rafael
    groups: seat
    append: yes

- name: software | window-manager | start seatd daemon
  tags: wayland,sway
  systemd:
    name: seatd
    enabled: yes
    state: started

- name: software | window-manager | ensure Sway dir exist
  tags: wayland,sway
  file:
    path: /home/rafael/.config/sway
    state: directory
    owner: rafael
    group: rafael
    mode: 0700

- name: software | window-manager | copy Sway dotfiles
  tags: wayland,sway
  copy:
    src: /home/ansible/git/dotfiles/i3-sway/{{ item.src }}
    dest: /home/rafael/.config/sway/{{ item.dest }}
    remote_src: true
    owner: rafael
    group: rafael
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'i3bang.rb',    dest: 'i3bang.rb', mode: '0700' }
    - { src: '_config_sway', dest: '_config',   mode: '0600' }

- name: software | window-manager | generate Sway config from Ruby script
  tags: wayland,sway
  become_user: rafael
  command:
    cmd: ruby /home/rafael/.config/sway/i3bang.rb
    creates: /home/rafael/.config/sway/config

- name: software | window-manager | install general packages
  tags: wayland,sway
  package:
    name:
      - xorg-xwayland  # run X clients under Wayland
      - wl-clipboard   # clipboard utils
      - waycheck       # Wayland protocols implementation status
      - wtype          # "xdotool type" for Wayland

- name: software | window-manager | install general packages from AUR
  tags: wayland,sway
  become_user: aurman
  kewlfft.aur.aur:
    name: autotiling  # script to switch h/v window orientation
  when: ansible_facts['distribution'] == "Archlinux"
