- name: software | xdg-desktop-portal | install portals
  tags: wayland,portals
  package:
    name:
      - xdg-desktop-portal      # XDG Desktop portal
      - xdg-desktop-portal-wlr  # xdg-desktop-portal backend for wlroots
      - xdg-desktop-portal-gtk  # xdg-desktop-portal backend using GTK

- name: software | xdg-desktop-portal | ensure xdg-desktop-portal dir exists
  tags: wayland,portals
  file:
    path: /home/rafael/.config/xdg-desktop-portal
    state: directory
    owner: rafael
    group: rafael
    mode: 0700

- name: software | xdg-desktop-portal | copy xdg-desktop-portal dotfile
  tags: wayland,portals
  copy:
    remote_src: true
    src: /home/ansible/git/dotfiles/xdg-desktop-portal/sway-portals.conf
    dest: /home/rafael/.config/xdg-desktop-portal/sway-portals.conf
    owner: rafael
    group: rafael
    mode: 0600
  notify: software | xdg-desktop-portal | restart xdg-desktop-portals user systemd services

#- name: software | xdg-desktop-portal | enable xdg-desktop-portals user services
#  tags: wayland,portals
#  become_user: rafael
#  systemd:
#    name: "{{ item }}"
#    enabled: true
#    scope: user
#  loop:
#    - "xdg-desktop-portal"
#    - "xdg-desktop-portal-wlr"
#    - "xdg-desktop-portal-gtk"

- name: software | xdg-desktop-portal | copy XDG MIME dotfile
  tags: wayland,portals
  copy:
    remote_src: true
    src: /home/ansible/git/dotfiles/xdg-desktop-portal/mimeapps.list
    dest: /home/rafael/.config/mimeapps.list
    owner: rafael
    group: rafael
    mode: 0600
