# load distro-specific variables
- name: load distro-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_facts['distribution'] }}.yml"
    - "{{ ansible_facts['os_family'] }}.yml"
    - "default.yml"
    skip: true  # prevents crashing if absolutely no matching files exist
  tags: always

- block:
    # software
    - import_tasks: software/packages.yml    # install Vim
