- name: software | terminal text editor | install Neovim
  tags: vim
  package:
    name: neovim
    state: latest

- name: software | terminal text editor | create vim symlink
  tags: vim
  file:
    src: /usr/bin/nvim
    path: /usr/bin/vim
    state: link

- name: software | terminal | ensure Neovim dir exist
  tags: vim
  file:
    path: /home/rafael/.config/nvim/{{ item }}
    state: directory
    owner: rafael
    group: rafael
    mode: 0700
  with_items:
    - lua/config
    - lua/plugins

- name: software | terminal text editor | copy Neovim dotfiles
  tags: vim
  copy:
    remote_src: yes
    src: /home/rafael/git/dotfiles/nvim/{{ item }}
    dest: /home/rafael/.config/nvim/{{ item }}
    owner: rafael
    group: rafael
    mode: 0600
  with_items:
    - init.vim
    - lua/plugins.lua
