- name: system | bluetooth | BlueZ install
  tags: system,bluetooth
  package:
    name:
      - bluez               # Bluetooth protocol stack
      - bluez-utils         # bluetoothctl utility

- name: system | bluetooth | Blueman (GTK+ Bluetooth manager)
  tags: system,bluetooth
  package:
    name: blueman           # blueman (Bluetooth manager)
