- name: systemd | cleanup | check for orphan packages
  tags: system,cleanup,pacman
  ansible.builtin.command: pacman -Qtdq
  register: orphans
  changed_when: false
  failed_when: orphans.rc not in [0, 1]  # 1 means no orphans found
  when: ansible_facts['distribution'] == "Archlinux"

- name: systemd | cleanup | remove orphan packages
  tags: system,cleanup,pacman
  community.general.pacman:
    name: "{{ orphans.stdout_lines }}"
    state: absent
  when: orphans.rc == 0
  when: ansible_facts['distribution'] == "Archlinux"

- name: systemd | cleanup | ensure deprecated packages are uninstalled
  tags: system,cleanup,graveyard
  community.general.pacman:
    name:
      # package name:              # deprecated in favour of:
      - audacity                   # tenacity
      - brave-bin                  # [AUR] brave-origin-bin
      - brave-beta-bin             # [AUR] brave-origin-bin
      - brave-origin-beta-bin      # [AUR] brave-origin-bin
      - docker                     # podman
      - emacs                      # emacs-wayland
      - firefox-developer-edition  # [AUR] zen-browser-bin
      - slack-desktop              # [AUR] slack-desktop-wayland
      - sway                       # [AUR] swayfx-git
      - swaylock                   # hyprlock
      - swaylock-effects           # hyprlock
      - thunderbird                # [AUR] betterbird-bin
      - vlc                        # [AUR] vlc-git (version 4.x)
      - vlc-plugins-base           # [AUR] vlc-git (version 4.x)
      - vlc-plugins-extra          # [AUR] vlc-git (version 4.x)
    state: absent

- name: system | grub | remove kernel parameters
  tags: system,cleanup,grub
  replace:
    path: /etc/default/grub
    # matches the parameter and any preceding/trailing spaces, up to the next space or quote
    regexp: '\s*{{ item | regex_escape }}(?=\s|")'
    replace: ''
  loop:
    - splash     # used for splash screen during boot
    - nomodeset  # used for GPU troubleshooting by disabling KMS
  notify: regenerate grub config
