- name: system | grub | install grub-btrfs
  tags: system,grub
  package:
    name:
      - inotify-tools  # prerequisite for grub-btrfs
      - grub-btrfs     # include snapshots at boot options

- name: system | grub | set path of snapshots in grub-btrfsd
  tags: system,grub
  lineinfile:
    path: /etc/systemd/system/grub-btrfsd.service
    line: 'ExecStart=/usr/bin/grub-btrfsd --syslog /.snapshot'
    state: present
    regexp: '^ExecStart=.*'
    insertafter: '^\[Service\]$'

- name: system | grub | include BTRFS snapshots in GRUB
  tags: system,grub
  systemd:
    name: grub-btrfsd
    enabled: yes
    state: started

- name: system | grub | set GRUB options
  tags: system,grub
  become: yes
  lineinfile:
    backup: true
    path: /etc/default/grub
    line: "{{ item.line }}"
    state: present
    regexp: "{{ item.regex }}"
  with_items:
    - { line: "GRUB_DEFAULT=0",            regex: "^GRUB_DEFAULT=.*$" }
    - { line: "GRUB_TIMEOUT=0",            regex: "^GRUB_TIMEOUT=.*$" }
    - { line: "GRUB_TIMEOUT_STYLE=hidden", regex: "^GRUB_TIMEOUT_STYLE=.*$" }
  register: grub

- name: system | grub | regenerate GRUB config file
  tags: system,grub
  become: yes
  shell:
    cmd: grub-mkconfig -o /efi/EFI/arch/grub/grub.cfg
  when: grub.changed
