- name: system | keyboard remap | install Rust
  tags: keyboard,rust,xremap
  package:
    name: rust

- name: system | keyboard remap | install xremap
  tags: keyboard,xremap
  community.general.cargo:
    name: xremap

#cargo install xremap --features sway

- name: system | keyboard remap | add user to input group
  tags: keyboard,xremap
  user:
    name: rafael
    append: yes
    groups: input
