- name: system | keyboard remap | install Rust
  tags: keyboard,rust,xremap
  package:
    name: rust

- name: system | keyboard remap | install xremap
  tags: keyboard,xremap
  community.general.cargo:
    name: xremap

#cargo install xremap --features sway

- name: system | keyboard remap | add user to input group
  tags: keyboard,xremap
  user:
    name: rafael
    append: yes
    groups: input

- name: system | keyboard remap | copy udev/rules.d file
  tags: keyboard,xremap
  copy:
    remote_src: true
    src: /home/rafael/git/dotfiles/udev/rules.d/input.rules
    dest: /etc/udev/rules.d/input.rules
    owner: root
    group: root
    mode: 0644

- name: system | keyboard remap | ensure xremap dir exist
  tags: keyboard,xremap
  file:
    path: /home/rafael/.config/xremap
    state: directory
    owner: rafael
    group: rafael
    mode: 0700

- name: system | keyboard remap | copy xremap dotfile
  tags: keyboard,xremap
  copy:
    remote_src: true
    src: /home/rafael/git/dotfiles/xremap/config.yml
    dest: /home/rafael/.config/xremap/config.yml
    owner: rafael
    group: rafael
    mode: 0600
