- name: software | keyboard | fix cedilla in en_US locale
  tags: system,keyboard,cedilla
  ansible.builtin.replace:
    path: /usr/share/X11/locale/en_US.UTF-8/Compose
    regexp: "{{ item.find }}"
    replace: "{{ item.replace }}"
  with_items:
    - { find: 'ć', replace: 'ç' }
    - { find: 'Ć', replace: 'Ç' }
