- name: system | keyboard | set custom split keeb
  tags: keyboard
  package:
    name:
      #- evtest                         # used to get scan codes of each key
      - interception-caps2esc
      - interception-dual-function-keys

- name: system | udevmon | interception (space2meta)
  tags: udevmon,interception
  become_user: aurman
  aur:
    name:
      - interception-space2meta

- name: system | udevmon | copy udevmon config file
  tags: udevmon,interception
  copy:
    src: files/udevmon/udevmon.yaml
    dest: /etc/interception/udevmon.yaml
    owner: root
    group: root
    mode: 0644
  register: udevmon_config
