- name: system | networking | install NetworkManager
  tags: system,network
  package:
    name:
      - networkmanager                   # core package
      - nm-connection-editor             # GUI
      - network-manager-applet           # system tray applet

- name: system | networking | start NetworkManager daemon
  tags: system,network
  systemd:
    name: NetworkManager
    state: started
    enabled: yes

- name: system | networking | install Avahi
  tags: system,network
  package:
    name: avahi

- name: system | networking | start Avahi daemon
  tags: system,network
  systemd:
    name: avahi-daemon
    state: started
    enabled: yes

- name: system | networking | install network packages
  tags: system,network
  package:
    name:
      - net-tools                        # collection of base networking utilities
