- name: system | networking | install NetworkManager
  tags: system,network
  package:
    name:
      - networkmanager                   # core package
      - nm-connection-editor             # GUI
      - network-manager-applet           # system tray applet

- name: system | NetworkManager | start daemon
  tags: system,network
  systemd:
    name: NetworkManager
    state: started
    enabled: yes

- name: system | networking | install OpenVPN
  tags: system,network
  package:
    name:
      - openvpn                          # install OpenVPN
