- name: system | networking | NetworkManager install
  tags: system,network
  package:
    name:
      - networkmanager                   # core package
      - nm-connection-editor             # GUI
    state: latest

- name: system | NetworkManager | start daemon
  tags: system,network
  systemd:
    name: NetworkManager
    state: started
    enabled: yes
