- name: system | networking | NetworkManager install
  package:
    name: networkmanager
    state: latest

- name: system | NetworkManager | start daemon
  systemd:
    name: NetworkManager
    state: started
    enabled: yes
