- name: system | network | install network packages
  tags: system,network
  package:
    name:
      - net-tools           # collection of base networking utilities
      - inetutils           # collection of common network programs
      - nmap                # network discovery + security auditing
      - ufw                 # manage netfilter firewall
      #- openresolv          # resolv.conf management framework
      - systemd-resolvconf  # systemd resolvconf replacement

- name: system | network | install NetworkManager
  tags: system,network
  package:
    name:
      - networkmanager          # core package
      - nm-connection-editor    # GUI
      - network-manager-applet  # system tray applet
      - networkmanager-dmenu    # integration with dmenu/Rofi

- name: system | network | ensure networkmanager-dmenu dir exists
  tags: system,network
  file:
    path: /home/rafael/.config/networkmanager-dmenu
    state: directory
    owner: rafael
    group: rafael
    mode: 0700

- name: system | network | copy networkmanager-dmenu dotfile
  tags: system,network
  copy:
    src: /home/ansible/git/dotfiles/networkmanager-dmenu/config.ini
    dest: /home/rafael/.config/networkmanager-dmenu/config.ini
    remote_src: true
    owner: rafael
    group: rafael
    mode: 0600

- name: system | network | start NetworkManager daemon
  tags: system,network
  systemd:
    name: NetworkManager
    state: started
    enabled: yes

- name: system | network | install Avahi
  tags: system,network
  package:
    name: avahi

- name: system | network | start Avahi daemon
  tags: system,network
  systemd:
    name: avahi-daemon
    state: started
    enabled: yes
