- name: system | printer | install CUPS & tools
  tags: system,printer
  package:
    name:
      - cups                    # CUPS
      - cups-pdf                # print as PDF
      - system-config-printer   # GUI for CUPS
      - hplip                   # HP driver

- name: system | printer | start CUPS daemon
  tags: system,printer
  systemd:
    name: cups
    state: started
    enabled: yes

- name: system | printer | template CUPS printers config file
  tags: system,printer
  ansible.builtin.template:
    src: /home/ansible/git/dotfiles/cups/printers.conf
    dest: /etc/cups/printers.conf
    owner: root
    group: lp
    mode: '0600'
  vars:
    ip_printer_lbic_laserjet_p3005dn: "{{ lookup('pipe', 'sudo -u rafael pass show ip/printer_lbic') | trim }}"
  # hide the output to prevent the real IP address from being printed in the Ansible logs
  no_log: true
  notify: system | printer | restart cups systemd service

- name: system | printer | copy CUPS printers PPD file
  tags: system,printer
  copy:
    src: /home/ansible/git/dotfiles/cups/{{ item }}
    dest: /etc/cups/ppd/{{ item }}
    remote_src: true
    owner: root
    group: lp
    mode: 0644
  loop:
    - HP-LaserJet-p3005.ppd
  notify: system | printer | restart CUPS systemd service
