- name: system | printer | install CUPS & tools
  tags: system,printer
  package:
    name:
      - cups                    # CUPS
      - cups-pdf                # print as PDF
      - system-config-printer   # GUI for CUPS
      - hplip                   # HP driver

- name: system | printer | start CUPS daemon
  tags: system,printer
  systemd:
    name: cups
    state: started
    enabled: yes
