- name: system | printer | install CUPS
  tags: system,printer
  package:
    name:
      - cups
      - cups-pdf

- name: system | printer | start CUPS daemon
  tags: system,printer
  systemd:
    name: cups
    state: started
    enabled: yes

- name: system | printer | install GUI for CUPS
  tags: system,printer
  package:
    name: system-config-printer

- name: system | printer | install HP driver
  tags: system,printer
  package:
    name: hplip
