- name: system | udevmon | interception-tools (caps2esc)
  tags: udevmon,interception
  package:
    name:
      - interception-tools
      - interception-caps2esc

- name: system | udevmon | interception (space2meta)
  tags: udevmon,interception
  become_user: aurman
  aur:
    name:
      - interception-space2meta

- name: system | udevmon | copy udevmon config file
  tags: udevmon,interception
  copy:
    src: files/udevmon/udevmon.yaml
    dest: /etc/interception/udevmon.yaml
    owner: root
    group: root
    mode: 0644

- name: system | udevmon | start daemon
  tags: udevmon,interception
  systemd:
    name: udevmon
    state: started
    enabled: yes
