- name: system | udevmon | interception-tools (caps2esc / dual-function-keys)
  tags: udevmon,interception
  package:
    name:
      - interception-tools
      - interception-caps2esc
      - interception-dual-function-keys

- name: system | udevmon | interception (space2meta)
  tags: udevmon,interception
  become_user: aurman
  aur:
    name:
      - interception-space2meta

- name: system | udevmon | copy udevmon config file
  tags: udevmon,interception
  copy:
    src: files/udevmon/udevmon.yaml
    dest: /etc/interception/udevmon.yaml
    owner: root
    group: root
    mode: 0644
  register: udevmon_config

- name: system | udevmon | restart udevmon daemon
  tags: udevmon,interception
  systemd:
    name: udevmon
    state: restarted
    enabled: yes
  when: udevmon_config.changed

- name: system | udevmon | start udevmon daemon
  tags: udevmon,interception
  systemd:
    name: udevmon
    state: started
    enabled: yes
