- name: system | Wi-Fi | install Wi-Fi packages
  tags: system,wifi
  package:
    name:
      - iproute2                    # IP Routing Utilities
      - util-linux                  # provides rfkill (and much more)
      - "{{ wpa_supplicant_pkg }}"  # WPA Supplicant
      - iw                          # nl80211-based CLI config util
  when: wifi

- name: system | Wi-Fi | eduroam ensure dir exist
  tags: wifi,eduroam
  ansible.builtin.file:
    path: /home/rafael/.config/cat_installer
    state: directory
    owner: rafael
    group: rafael
    mode: 0700
  when: wifi

- name: system | Wi-Fi | eduroam download eduroam script
  tags: wifi,eduroam
  ansible.builtin.get_url:
    url: "https://cat.eduroam.org/user/API.php?action=downloadInstaller&lang=en&profile=1178&device=linux&generatedfor=user&openroaming=0"
    dest: /home/rafael/.config/cat_installer/
    owner: rafael
    group: rafael
    mode: '0700'
  when: wifi
  register: eduroam_download

- name: system | Wi-Fi | eduroam install CA certificate
  tags: wifi,eduroam
  become_user: rafael
  ansible.builtin.command:
    argv:
      - python
      - "{{ eduroam_download.dest }}"
      - --username
      - "{{ lookup('pipe', 'sudo -u rafael pass show eduroam/login') }}"
      - --password
      - "{{ lookup('pipe', 'sudo -u rafael pass show eduroam/password') }}"
      - --silent
    chdir: /home/rafael/.config/cat_installer
    creates: /home/rafael/.config/cat_installer/ca.pem
  when: wifi
