- name: system | Wi-Fi | install Wi-Fi packages
  tags: system,wifi
  package:
    name:
      - iproute2                    # IP Routing Utilities
      - util-linux                  # provides rfkill (and much more)
      - "{{ wpa_supplicant_pkg }}"  # WPA Supplicant
      - iw                          # nl80211-based CLI config util
  when: wifi

- name: system | Wi-Fi | eduroam ensure dir exist
  tags: wifi,eduroam
  ansible.builtin.file:
    path: /home/rafael/.config/cat_installer
    state: directory
    owner: rafael
    group: rafael
    mode: 0700
  when: wifi

- name: system | Wi-Fi | eduroam register the JSON response
  tags: wifi,eduroam
  ansible.builtin.uri:
    url: "https://cat.eduroam.org/user/API.php?action=downloadInstaller&lang=en&profile=1178&device=linux&generatedfor=user&openroaming=0"
    body_format: json
  register: json_output
  when: wifi

- name: system | Wi-Fi | eduroam parse JSON and register filename
  tags: wifi,eduroam
  set_fact:
    filename: "{{ (json_output['content_disposition'] | split('\"'))[1] }}"
  when: wifi

- name: system | Wi-Fi | eduroam download eduroam script
  tags: wifi,eduroam
  ansible.builtin.get_url:
    url: "https://cat.eduroam.org/user/API.php?action=downloadInstaller&lang=en&profile=1178&device=linux&generatedfor=user&openroaming=0"
    dest: /home/rafael/.config/cat_installer/{{ filename }}
    owner: rafael
    group: rafael
    mode: '0700'
  when: wifi
