- name: keyboard | lan-mouse | restart user systemd service
  tags: keyboard,lan-mouse
  become_user: rafael
  ansible.builtin.systemd:
    name: lanmouse
    scope: user
    state: restarted

- name: keyboard | KMonad | restart global systemd service
  tags: keyboard,kmonad
  ansible.builtin.systemd:
    name: kmonad
    state: restarted

- name: keyboard | interception | restart udevmon systemd service
  tags: keyboard,interception
  ansible.builtin.systemd:
    name: udevmon
    state: restarted

- name: keyboard | kanata | disable user systemd service
  tags: keyboard,kanata
  become_user: rafael
  ansible.builtin.systemd:
    name: kanata
    enabled: false
    scope: user

- name: keyboard | kanata | enable global systemd service
  tags: keyboard,kanata
  ansible.builtin.systemd:
    name: kanata
    enabled: true

- name: keyboard | xremap | disable user systemd service (to be started by XDG Autostart)
  tags: keyboard,xremap
  become_user: rafael
  ansible.builtin.systemd:
    name: xremap
    enabled: false
    scope: user

- name: keyboard | ydotool | restart user systemd service
  tags: keyboard,ydotool
  become_user: rafael
  ansible.builtin.systemd:
    name: ydotool
    enabled: true
    state: restarted
    scope: user

- name: keyboard | kanata | try-restart systemd user service
  tags: keyboard,kanata
  become_user: rafael
  ansible.builtin.command: systemctl try-restart kanata.service --user

- name: keyboard | kanata | try-restart systemd global service
  tags: keyboard,kanata
  ansible.builtin.command: systemctl try-restart kanata.service

- name: keyboard | xremap | try-restart systemd user service
  tags: keyboard,xremap
  become_user: rafael
  ansible.builtin.command: systemctl try-restart xremap.service --user

- name: keyboard | udev/hwdb | restart systemd-hwdb-update systemd service
  tags: keyboard,hwdb
  ansible.builtin.systemd:
    name: systemd-hwdb-update
    state: restarted
    enabled: true

- name: keyboard | udev/hwdb | rebuild the hardware database index (hwdb.bin)
  tags: keyboard,hwdb
  command: systemd-hwdb update

- name: keyboard | udev/hwdb | update udev rules on the fly
  tags: keyboard,hwdb
  command: udevadm trigger
