- name: keyboard | lan-mouse | restart user systemd service
  become_user: rafael
  ansible.builtin.systemd:
    name: lanmouse
    scope: user
    state: restarted

- name: keyboard | KMonad | restart KMonad global systemd service
  tags: keyboard,kmonad
  systemd:
    name: kmonad
    state: restarted

- name: keyboard | interception | restart udevmon systemd service
  tags: keyboard,interception
  systemd:
    name: udevmon
    state: restarted

- name: keyboard | xremap | try-restart xremap systemd user service
  tags: keyboard,xremap
  become_user: rafael
  ansible.builtin.command: systemctl try-restart xremap.service --user

- name: keyboard | xremap | try-restart xremap systemd global service
  tags: keyboard,xremap
  ansible.builtin.command: systemctl try-restart xremap.service
