- name: keyboard | lan-mouse | restart user systemd service
  become_user: rafael
  ansible.builtin.systemd:
    name: lanmouse
    scope: user
    state: restarted
    daemon_reload: false

- name: keyboard | KMonad | restart KMonad global systemd service
  tags: keyboard,kmonad
  systemd:
    name: kmonad
    state: restarted
