- name: handler | get UID of the user
  ansible.builtin.getent:
    database: passwd
    key: rafael

- name: reload systemd services (system scope)
  systemd:
    daemon_reload: true
    scope: system

- name: reload user systemd services (ansible)
  become_user: ansible
  systemd:
    daemon_reload: true
    scope: user

- name: reload user systemd services (rafael)
  become_user: rafael
  systemd:
    daemon_reload: true
    scope: user

- name: update udev rules on the fly
  command: udevadm control --reload-rules

- import_tasks: keyboard.yml
- import_tasks: software.yml
- import_tasks: system.yml
