- name: software | semaphore | restart user systemd service
  tags: semaphore
  become_user: ansible
  systemd:
    name: semaphore
    state: restarted
    enabled: true
    scope: user

- name: software | pomodoro | restart tomat user systemd service
  tags: pomodoro
  become_user: rafael
  systemd:
    name: tomat
    state: restarted
    enabled: true
    scope: user

- name: software | xdg-desktop-portal | restart xdg-desktop-portals user systemd services
  tags: wayland,portals
  become_user: rafael
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: true
    scope: user
  loop:
    - "xdg-desktop-portal"
    - "xdg-desktop-portal-wlr"
    - "xdg-desktop-portal-gtk"
