- name: software | media | restart MPD user systemd service
  tags: media,audio
  become_user: rafael
  ansible.builtin.systemd:
    name: mpd
    enabled: true
    state: restarted
    scope: user

- name: software | pomodoro | restart tomat user systemd service
  tags: pomodoro
  become_user: rafael
  systemd:
    name: tomat
    state: restarted
    enabled: true
    scope: user

- name: software | power manager | enable PowerTOP systemd service
  tags: power,powertop
  ansible.builtin.systemd:
    name: powertop
    enabled: true
    state: started
    scope: system

- name: software | semaphore | restart user systemd service
  tags: semaphore
  become_user: ansible
  systemd:
    name: semaphore
    state: restarted
    enabled: true
    scope: user

- name: software | xdg-desktop-portal | restart xdg-desktop-portals user systemd services
  tags: wayland,portals
  become_user: rafael
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: true
    scope: user
  loop:
    - "xdg-desktop-portal"
    - "xdg-desktop-portal-wlr"
    - "xdg-desktop-portal-gtk"
