- name: system | grub | regenerate GRUB config file
  tags: system,grub
  shell:
    cmd: grub-mkconfig -o /efi/EFI/arch/grub/grub.cfg

- name: system | power | restart logind service
  tags: power
  systemd:
    name: systemd-logind
    state: restarted

- name: system | mouse | restart LogiOps systemd service
  tags: mouse,logiops
  systemd:
    name: logid
    state: restarted
