- name: system | power | restart logind service
  tags: power
  systemd:
    name: systemd-logind
    state: restarted

- name: system | mouse | restart LogiOps systemd service
  tags: mouse,logiops
  systemd:
    name: logid
    enabled: yes
    state: started
