- name: system | power | restart logind service
  tags: power
  systemd:
    name: systemd-logind
    state: restarted

- name: system | mouse | restart LogiOps systemd service
  tags: mouse,logiops
  systemd:
    name: logid
    state: restarted

- name: system | printer | restart CUPS systemd service
  tags: printer,cups
  systemd:
    name: cups
    state: restarted
