- name: init | ssh keys | create dir
  tags: ansible,openssh,ssh-keys
  file:
    path: /home/ansible/.ssh
    state: directory
    owner: ansible
    group: ansible
    mode: 0700

- name: init | ssh keys | generate keys
  tags: ansible,openssh,ssh-keys
  openssh_keypair:
    path: /home/ansible/.ssh/id_ed25519
    type: ed25519
    state: present
    owner: ansible
    group: ansible
    comment: "Ansible"

- name: init | ssh keys | create known_hosts & authorized_keys dirs
  tags: ansible,openssh,ssh-keys
  copy:
    content: ""
    dest: "{{ item }}"
    force: no
    owner: ansible
    group: ansible
    mode: 0600
  with_items:    
    - /home/ansible/.ssh/known_hosts
    - /home/ansible/.ssh/authorized_keys

- name: init | ssh keys | copy pub ssh key
  tags: ansible,openssh,ssh-keys
  authorized_key:
    key: "{{ lookup('file', '/home/ansible/.ssh/id_ed25519.pub') }}"
    user: ansible
    state: present
